wavesplatform/Waves

azure/README.md
azure/azuredeploy.json
azure/azuredeploy.parameters.json
azure/build.sh
azure/metadata.json

Template and build files for Azure Quickstart Templates. The URI buttons in README.md point to _your_ repository. Please validate after merge Azure build process runs as expected. If Waves teams pushes to Azure template repository, I can change the buttons' URI to the Azure repository and update the folder name.

Waves for Azure

---

build.sbt
src/main/scala/com/wavesplatform/Application.scala
src/test/scala/scorex/waves/TestingCommons.scala

Some important initialization stuff has been moved to Application companion object

fixed issue with incorrect AddressScheme initialization

---

build.sbt
lock.sbt
pack.sbt

JavaAppPackaging plugin was enabled.

Project dependencies were reloced to 1.4.6-SNAPSHOT version of Scorex.

---

src/main/scala/com/wavesplatform/matcher/market/OrderBookActor.scala
src/main/scala/com/wavesplatform/matcher/model/MatcherModel.scala
src/main/scala/com/wavesplatform/matcher/model/OrderBook.scala
src/test/resources/application.conf
src/test/scala/com/wavesplatform/matcher/market/OrderBookActorSpecification.scala

Matching with invalid order

---

src/main/scala/scorex/waves/http/DebugApiRoute.scala

Balance Distribution

---

src/main/scala/scorex/app/RunnableApplication.scala
src/main/scala/scorex/block/Block.scala
src/main/scala/scorex/consensus/ConsensusModule.scala
src/main/scala/scorex/consensus/nxt/WavesConsensusModule.scala
src/main/scala/scorex/network/InMemoryBlockSeq.scala
src/main/scala/scorex/transaction/SimpleTransactionModule.scala
src/main/scala/scorex/transaction/TransactionModule.scala
src/main/scala/scorex/transaction/state/database/blockchain/StoredBlockchain.scala
src/main/scala/scorex/waves/transaction/WavesTransactionModule.scala
src/test/scala/com/wavesplatform/matcher/market/MatcherActorSpecification.scala
src/test/scala/scorex/ActorTestingCommons.scala
src/test/scala/scorex/lagonaki/TransactionTestingCommons.scala
src/test/scala/scorex/lagonaki/integration/api/TransactionsAPISpecification.scala
src/test/scala/scorex/lagonaki/mocks/TestBlock.scala
src/test/scala/scorex/lagonaki/unit/CoordinatorCheckpointSpecification.scala
src/test/scala/scorex/lagonaki/unit/SimpleTransactionModuleSpecification.scala
src/test/scala/scorex/network/BlockchainSynchronizerSpecification.scala
src/test/scala/scorex/network/InMemorySeqSpecification.scala
src/test/scala/scorex/transaction/UnconfirmedPoolSynchronizerSpecification.scala

T361 make block dto

---

src/main/scala/scorex/transaction/state/database/blockchain/LeaseExtendedState.scala
src/test/scala/com/wavesplatform/settings/FeesSettingsSpecification.scala
src/test/scala/scorex/lagonaki/integration/StoredStateSpecification.scala
src/test/scala/scorex/transaction/FeeCalculatorSpecification.scala

Incorrect generation balance calculation in state was fixed.

---

src/test/scala/scorex/lagonaki/unit/MessageHandlerSpec.scala
src/test/scala/scorex/lagonaki/unit/MessageSpecification.scala
src/test/scala/scorex/lagonaki/unit/UnitTestConfig.scala

First you have to merge https://github.com/wavesplatform/Waves/pull/228

T523 message handler spec to unit

---

src/test/scala/scorex/lagonaki/unit/BlockSpecification.scala
src/test/scala/scorex/lagonaki/unit/MessageSpecification.scala
src/test/scala/scorex/lagonaki/unit/UnitTestConfig.scala

First you have to merge https://github.com/wavesplatform/Waves/pull/228

T518 block specification to unit

---

lock.sbt
project/Dependencies.scala
src/main/scala/com/wavesplatform/mining/Miner.scala
src/main/scala/com/wavesplatform/network/NetworkServer.scala
src/main/scala/com/wavesplatform/network/PeerDatabaseImpl.scala

MVStore version bump
Task cancel without interrupt for MVStore safety

PeerDatabase fixed

---

src/it/scala/com/wavesplatform/it/BlacklistTestSuite.scala
src/it/scala/com/wavesplatform/it/Docker.scala
src/it/scala/com/wavesplatform/it/NetworkSeparationTestSuite.scala
src/it/scala/com/wavesplatform/it/api/NodeApi.scala

Integration tests expectation tuned to be more realistic

Fixed timeout exception handling in NodeApi in integration tests

---

build.sbt
src/main/resources/application.conf

Default blacklist time was set to 1m

Version was set to 0.7.2

---

src/main/scala/scorex/api/http/TransactionsApiRoute.scala

Minor changes to documentation

Renamed parameters for /transactions/info and /unconfirmed/info

---

src/main/scala/scorex/api/http/alias/AliasApiRoute.scala

Minor documentation improvements. Again.

Added details to alias related HTTP API methods documentation

---

src/main/scala/scorex/block/MicroBlock.scala
src/test/scala/scorex/lagonaki/unit/MicroBlockSpecification.scala

MicroBlock creation fix

---

src/main/scala/com/wavesplatform/utils/ApplicationStopReason.scala
src/main/scala/com/wavesplatform/utils/package.scala
src/package/systemd.service
src/package/upstart.conf

#define ENOSYS          38      /* Function not implemented */

NODE-164 error code from errno.h RedHat 7.3

---

src/main/scala/com/wavesplatform/Coordinator.scala
src/main/scala/com/wavesplatform/general/BlockVersion.scala
src/main/scala/com/wavesplatform/mining/Miner.scala
src/main/scala/com/wavesplatform/settings/BlockchainSettings.scala
src/main/scala/com/wavesplatform/state2/diffs/BlockDiffer.scala
src/test/scala/scorex/transaction/NgStateTest.scala

NODE-193: Cleanup usages of enableBlockVersion3
NODE-197: additional NgState tests

Node 04 ng

---

src/main/scala/com/wavesplatform/Application.scala
src/main/scala/com/wavesplatform/features/BlockchainFeatures.scala
src/main/scala/com/wavesplatform/features/FeatureProvider.scala
src/main/scala/com/wavesplatform/history/HistoryWriterImpl.scala
src/main/scala/com/wavesplatform/history/StorageFactory.scala
src/test/scala/com/wavesplatform/UtxPoolSpecification.scala
src/test/scala/com/wavesplatform/history/BlockchainUpdaterBlockMicroblockSequencesSameTransactionsTest.scala
src/test/scala/com/wavesplatform/history/BlockchainUpdaterBlockOnlyTest.scala
src/test/scala/com/wavesplatform/history/BlockchainUpdaterMicroblockSunnyDayTest.scala
src/test/scala/com/wavesplatform/history/DomainScenarioDrivenPropertyCheck.scala
src/test/scala/com/wavesplatform/history/package.scala
src/test/scala/com/wavesplatform/http/ConsensusRouteSpec.scala
src/test/scala/com/wavesplatform/state2/diffs/package.scala
src/test/scala/scorex/settings/TestFunctionalitySettings.scala
src/test/scala/scorex/transaction/HistoryWriterTest.scala

Auto shutdown implemented

---

build.sbt

Adding options for removing intermediate containers.
https://github.com/marcuslonnberg/sbt-docker

NODE-204 add removeIntermediateContainers to build.sbt

---

src/main/resources/application.conf
src/main/scala/com/wavesplatform/Application.scala
src/main/scala/com/wavesplatform/network/NetworkServer.scala
src/main/scala/com/wavesplatform/network/PeerDatabase.scala
src/main/scala/com/wavesplatform/network/PeerDatabaseImpl.scala
src/main/scala/com/wavesplatform/network/client/LegacyChannelInitializer.scala
src/main/scala/com/wavesplatform/settings/NetworkSettings.scala
src/main/scala/scorex/api/http/PeersApiRoute.scala
src/test/scala/com/wavesplatform/network/LegacyFrameCodecSpec.scala
src/test/scala/com/wavesplatform/network/MessageCodecSpec.scala

Node restart on NoRouteToHostException was added

NODE-58: In addtion to blacklisting suspension of hosts was added

---

src/main/scala/com/wavesplatform/network/Handshake.scala
src/main/scala/com/wavesplatform/network/HandshakeHandler.scala
src/main/scala/com/wavesplatform/network/NetworkServer.scala
src/main/scala/com/wavesplatform/network/client/LegacyChannelInitializer.scala
src/test/scala/com/wavesplatform/network/HandshakeDecoderSpec.scala

The reason is the HandshakeDecoder read a handshake multiple times.

NODE-209 A handshake decoding error

---

src/main/scala/com/wavesplatform/Application.scala
src/main/scala/com/wavesplatform/metrics/Metrics.scala

NODE-239 Report settings to InfluxDB

---

src/it/scala/com/wavesplatform/it/ValidChainGenerationSpec.scala
src/it/scala/com/wavesplatform/it/WideStateGenerationSpec.scala

NODE-252: Speed up tests: Merge ValidChainGenerationSpec and WideStateGeneratorSpec

---

src/it/scala/com/wavesplatform/it/IntegrationSuiteWithThreeAddresses.scala
src/it/scala/com/wavesplatform/it/MatcherTestSuite.scala
src/it/scala/com/wavesplatform/it/NetworkSeparationTestSuite.scala
src/main/scala/com/wavesplatform/Coordinator.scala
src/main/scala/com/wavesplatform/history/HistoryWriterImpl.scala
src/main/scala/com/wavesplatform/state2/BlockchainUpdaterImpl.scala
src/main/scala/scorex/transaction/BlockchainUpdater.scala
src/main/scala/scorex/transaction/package.scala
src/main/scala/scorex/waves/http/DebugApiRoute.scala

Reapply dropped blocks if extension application has been unsuccessful

Node 267 improve resolution of forks

---

src/main/scala/scorex/account/PublicKeyAccount.scala
src/test/scala/scorex/account/AccountSpecification.scala

Test on representation as an Address was added

Corrected string representation of PublicKeyAccount

---

src/it/scala/com/wavesplatform/it/MatcherTestSuite.scala
src/main/resources/application.conf
src/main/scala/com/wavesplatform/history/StorageFactory.scala
src/main/scala/com/wavesplatform/settings/WavesSettings.scala
src/main/scala/com/wavesplatform/utils/package.scala
src/main/scala/scorex/utils/Time.scala

Parameter mvstore-page-split-size was added to configuration

Default mvstore page split size was set to 4kb

---

src/it/scala/com/wavesplatform/it/MicroblocksFeeTestSuite.scala
src/it/scala/com/wavesplatform/it/activation/NotActivateFeatureTestSuite.scala
src/main/scala/com/wavesplatform/Application.scala
src/main/scala/com/wavesplatform/network/CoordinatorHandler.scala
src/main/scala/com/wavesplatform/network/ExtensionBlocksLoader.scala
src/main/scala/com/wavesplatform/network/ExtensionSignaturesLoader.scala
src/main/scala/com/wavesplatform/network/HistoryReplier.scala
src/main/scala/com/wavesplatform/network/OptimisticExtensionLoader.scala
src/main/scala/com/wavesplatform/network/PeerDatabase.scala
src/main/scala/com/wavesplatform/network/PeerDatabaseImpl.scala
src/main/scala/com/wavesplatform/network/RemoteScoreObserver.scala
src/main/scala/scorex/block/Block.scala
src/test/scala/com/wavesplatform/network/ExtensionBlocksLoaderSpec.scala
src/test/scala/com/wavesplatform/network/ExtensionSignaturesLoaderSpec.scala
src/test/scala/com/wavesplatform/network/RemoteScoreObserverSpec.scala
src/test/scala/scorex/lagonaki/mocks/TestBlock.scala

Issue was appeared once on devnet

NODE-308 Node did not receive extensions

---

build.sbt
src/it/resources/logback-test.xml
src/it/scala/com/wavesplatform/it/BlacklistTestSuite.scala
src/it/scala/com/wavesplatform/it/Docker.scala
src/it/scala/com/wavesplatform/it/MatcherTestSuite.scala
src/it/scala/com/wavesplatform/it/MicroblocksFeeTestSuite.scala
src/it/scala/com/wavesplatform/it/NetworkSeparationTestSuite.scala
src/it/scala/com/wavesplatform/it/NetworkUniqueConnectionsTestSuite.scala
src/it/scala/com/wavesplatform/it/NodeConfigs.scala
src/it/scala/com/wavesplatform/it/RollbackSpecSuite.scala
src/it/scala/com/wavesplatform/it/ValidChainGenerationSuite.scala
src/it/scala/com/wavesplatform/it/WideStateGenerationSuite.scala
src/it/scala/com/wavesplatform/it/activation/ActivationFeatureTestSuite.scala
src/it/scala/com/wavesplatform/it/api/MultipleNodesApi.scala
src/it/scala/com/wavesplatform/it/network/SimpleTransactionsSuite.scala
src/it/scala/com/wavesplatform/it/transactions/BaseTransactionSuite.scala
src/main/scala/com/wavesplatform/mining/Miner.scala
src/main/scala/scorex/block/Block.scala
src/main/scala/scorex/block/MicroBlock.scala

* Fixed an issue with race condition in Docker ( https://github.com/moby/moby/issues/20648 ), now we specify the subnet manually;
* Saving logs of it:testOnly into files;
* Quorum in tests is increased;
* Test fixes.

NODE-335 More stable tests

---

src/it/scala/com/wavesplatform/it/Docker.scala
src/it/scala/com/wavesplatform/it/MatcherTestSuite.scala
src/it/scala/com/wavesplatform/it/WideStateGenerationSuite.scala
src/it/scala/com/wavesplatform/it/activation/ActivationStatusRequest.scala
src/it/scala/com/wavesplatform/it/api/package.scala
src/main/scala/com/wavesplatform/Coordinator.scala
src/main/scala/com/wavesplatform/mining/Miner.scala
src/main/scala/com/wavesplatform/network/CoordinatorHandler.scala
src/main/scala/com/wavesplatform/network/ExtensionSignaturesLoader.scala
src/main/scala/com/wavesplatform/network/HistoryReplier.scala
src/main/scala/com/wavesplatform/network/MessageCodec.scala
src/main/scala/com/wavesplatform/network/NetworkServer.scala
src/main/scala/com/wavesplatform/network/OptimisticExtensionLoader.scala
src/main/scala/com/wavesplatform/network/RemoteScoreObserver.scala
src/main/scala/com/wavesplatform/network/messages.scala
src/main/scala/scorex/api/http/BlocksApiRoute.scala
src/main/scala/scorex/waves/http/DebugApiRoute.scala
src/test/scala/com/wavesplatform/network/RemoteScoreObserverSpec.scala

* A node doesn't break an extension loading when mining;
* A node doesn't mine a microblock during a block mining.

NODE-319 Node should not request an extension before a previous one is applied

---

src/it/resources/template.conf
src/it/scala/com/wavesplatform/it/WideStateGenerationSuite.scala
src/main/resources/application.conf
src/main/scala/com/wavesplatform/Coordinator.scala
src/main/scala/com/wavesplatform/network/BasicMessagesRepo.scala
src/main/scala/com/wavesplatform/network/CoordinatorHandler.scala
src/main/scala/com/wavesplatform/network/ExtensionBlocksLoader.scala
src/main/scala/com/wavesplatform/network/ExtensionSignaturesLoader.scala
src/main/scala/com/wavesplatform/network/MessageCodec.scala
src/main/scala/com/wavesplatform/network/NetworkServer.scala
src/main/scala/com/wavesplatform/network/OptimisticExtensionLoader.scala
src/main/scala/com/wavesplatform/network/RemoteScoreObserver.scala
src/main/scala/com/wavesplatform/network/TrafficLogger.scala
src/main/scala/com/wavesplatform/settings/NetworkSettings.scala
src/main/scala/scorex/network/message/MessageSpec.scala
src/test/scala/com/wavesplatform/settings/NetworkSettingsSpecification.scala
waves-testnet.conf

Also I added a logging for messages

NODE-361 An early breaking of extensions

---

src/it/resources/template.conf
src/main/resources/application.conf
src/main/resources/logback.xml
src/main/scala/com/wavesplatform/network/BasicMessagesRepo.scala
src/main/scala/com/wavesplatform/network/HistoryReplier.scala
src/main/scala/com/wavesplatform/network/MicroBlockSynchronizer.scala
src/main/scala/com/wavesplatform/network/NetworkServer.scala
src/main/scala/com/wavesplatform/network/PeerDatabase.scala
src/main/scala/com/wavesplatform/network/PeerDatabaseImpl.scala
src/main/scala/com/wavesplatform/network/PeerSynchronizer.scala
src/main/scala/com/wavesplatform/network/RxExtensionLoader.scala
src/main/scala/com/wavesplatform/network/RxScoreObserver.scala
src/main/scala/com/wavesplatform/network/TrafficLogger.scala
src/main/scala/com/wavesplatform/network/messages.scala
src/test/scala/com/wavesplatform/settings/NetworkSettingsSpecification.scala

* Improved logging in TrafficLogger (it ignored some messages before);
* TrafficLogger can ignore received and transmitted messages separately;
* A logging of a message code;
* Removed unnecessary logs.

NODE-381 Logs improvement

---

src/main/scala/com/wavesplatform/network/RxScoreObserver.scala

NODE-401 Removed an annoying log message

---

src/it/scala/com/wavesplatform/it/transactions/LeasingTransactionsSuite.scala
src/main/scala/scorex/transaction/lease/LeaseTransaction.scala

[Link to JIRA](https://wavesplatform.atlassian.net/browse/NODE-379)
By request from frontend devs I've made status values in JSON lowercase

NODE-379 fix update: made JSON strings lowercase

---

src/main/scala/com/wavesplatform/network/BasicMessagesRepo.scala
src/main/scala/com/wavesplatform/network/Handshake.scala
src/main/scala/com/wavesplatform/network/InboundConnectionFilter.scala
src/main/scala/com/wavesplatform/network/NetworkServer.scala
src/main/scala/com/wavesplatform/network/PeerDatabase.scala
src/main/scala/com/wavesplatform/network/PeerDatabaseImpl.scala
src/main/scala/com/wavesplatform/network/PeerSynchronizer.scala
src/test/scala/scorex/network/BlacklistParallelSpecification.scala
src/test/scala/scorex/network/BlacklistSpecification.scala
src/test/scala/scorex/network/peer/PeerDatabaseImplSpecification.scala

* Also closing the connection if a peer is suspended

NODE-422 NPE suspend peer

---

build.sbt
src/package/debian/postinst
src/package/debian/postrm
src/package/debian/preinst

* Install upstart script as an ordinary file
* Move rename `waves.conf` to `waves.conf.bak`
* Fix permissions for `application.ini`

DEB tweaks

---

src/main/resources/application.conf

Removed payment transaction fee from fee settings, also cleaned up tests

Cleaned up fee settings for the obsolete payment transaction

---

src/it/scala/com/wavesplatform/it/Docker.scala
src/it/scala/com/wavesplatform/it/MicroblocksGenerationSuite.scala
src/it/scala/com/wavesplatform/it/NodeImpl.scala
src/it/scala/com/wavesplatform/it/RollbackSpecSuite.scala
src/it/scala/com/wavesplatform/it/TransferSending.scala
src/it/scala/com/wavesplatform/it/WideStateGenerationSuite.scala
src/it/scala/com/wavesplatform/it/api/AsyncHttpApi.scala
src/it/scala/com/wavesplatform/it/api/AsyncNetworkApi.scala
src/it/scala/com/wavesplatform/it/api/Node.scala

NODE-444 Integration tests: send all transactions to multiple nodes and verify all were added

---

src/main/scala/com/wavesplatform/Application.scala
src/main/scala/scorex/api/http/CompositeHttpService.scala

JIRA: https://wavesplatform.atlassian.net/browse/NODE-491
Enabled HTTP logging (status + method + URL)

NODE-491 Enable logging in REST API

---

src/main/scala/scorex/api/http/CompositeHttpService.scala

HTTP OK responses now go to Debug log, and all others to Warning log

NODE-491 Tuned log levels (HTTP_OK => Debug, _ => Warn)

---

it/src/test/scala/com/wavesplatform/it/WideStateGenerationSuite.scala
src/main/resources/application.conf
src/main/scala/com/wavesplatform/Application.scala
src/main/scala/com/wavesplatform/UtxPool.scala
src/main/scala/com/wavesplatform/network/UtxPoolSynchronizer.scala
src/main/scala/com/wavesplatform/settings/SynchronizationSettings.scala
src/test/scala/com/wavesplatform/settings/SynchronizationSettingsSpecification.scala

NODE-510 Optimise UTX synchronization

---

build.sbt
it/src/main/resources/template.conf
src/main/scala/com/wavesplatform/features/BlockchainFeature.scala
src/main/scala/com/wavesplatform/features/FeatureProvider.scala
src/main/scala/com/wavesplatform/features/api/ActivationApiRoute.scala
src/main/scala/com/wavesplatform/history/HistoryWriterImpl.scala
src/main/scala/com/wavesplatform/settings/BlockchainSettings.scala
src/main/scala/com/wavesplatform/state2/BlockchainUpdaterImpl.scala
src/main/scala/scorex/transaction/NgHistoryReader.scala
src/test/scala/com/wavesplatform/settings/BlockchainSettingsSpecification.scala
src/test/scala/com/wavesplatform/state2/diffs/BlockDifferTest.scala
src/test/scala/scorex/settings/TestFunctionalitySettings.scala
src/test/scala/scorex/transaction/BlockchainUpdaterTest.scala
waves-devnet.conf

Fork parameter to doulbe approval and activation periods was implemented

---

src/main/scala/com/wavesplatform/history/HistoryWriterImpl.scala
src/main/scala/com/wavesplatform/history/StorageFactory.scala
src/main/scala/com/wavesplatform/state2/BlockchainUpdaterImpl.scala
src/main/scala/com/wavesplatform/state2/StateStorage.scala
src/main/scala/scorex/transaction/BlockchainUpdater.scala

https://wavesplatform.atlassian.net/browse/NODE-446
Synchronized stateHeight with blockchainHeight

NODE-446 /node/status returns state height that lags behind blockchain height

---

generator/src/main/resources/application.conf
generator/src/main/scala/com.wavesplatform.generator/NarrowTransactionGenerator.scala
generator/src/main/scala/com.wavesplatform.generator/utils/Gen.scala
it/src/main/resources/template.conf
it/src/main/scala/com/wavesplatform/it/api/AsyncHttpApi.scala
it/src/test/scala/com/wavesplatform/it/TransactionsApiSuite.scala
it/src/test/scala/com/wavesplatform/it/transactions/MassTransferTransactionSuite.scala
src/main/scala/com/wavesplatform/UtxPool.scala
src/main/scala/com/wavesplatform/features/BlockchainFeature.scala
src/main/scala/com/wavesplatform/state2/diffs/CommonValidation.scala
src/main/scala/com/wavesplatform/state2/diffs/MassTransferTransactionDiff.scala
src/main/scala/scorex/api/http/TransactionsApiRoute.scala
src/main/scala/scorex/api/http/assets/AssetsApiRoute.scala
src/main/scala/scorex/api/http/assets/MassTransferRequest.scala
src/main/scala/scorex/api/http/assets/SignedMassTransferRequest.scala
src/main/scala/scorex/transaction/TransactionFactory.scala
src/main/scala/scorex/transaction/assets/MassTransferTransaction.scala
src/test/scala/com/wavesplatform/TransactionGen.scala
src/test/scala/com/wavesplatform/UtxPoolSpecification.scala
src/test/scala/com/wavesplatform/state2/diffs/MassTransferTransactionDiffTest.scala
src/test/scala/scorex/transaction/MassTransferTransactionSpecification.scala

JIRA: https://wavesplatform.atlassian.net/browse/NODE-494

NODE-494 REST API for Mass Transfer

---

src/main/scala/scorex/api/http/CompositeHttpService.scala

Updated CompositeHttpService to use ScorexLogging instead of Akka logging

NODE-491 Made HTTP_OK logging possible without tweaking application.conf

---

it/src/test/scala/com/wavesplatform/it/transactions/BurnTransactionSuite.scala
src/main/scala/com/wavesplatform/state2/reader/SnapshotStateReader.scala

JIRA: https://wavesplatform.atlassian.net/browse/NODE-521
Filtered out zero-balance assets

NODE-521 Filter out assets with zero balances from /assets/balance response

---

it/src/main/scala/com/wavesplatform/it/api/SyncHttpApi.scala
it/src/test/scala/com/wavesplatform/it/transactions/BurnTransactionSuite2.scala

JIRA: https://wavesplatform.atlassian.net/projects/NODE/issues/NODE-561
Rewrite BurnTransactionSuite in sync way

Rewrite BurnTransactionSuite in sync way for NODE-561

---

generator/src/main/scala/com.wavesplatform.generator/NarrowTransactionGenerator.scala
generator/src/main/scala/com.wavesplatform.generator/utils/Gen.scala
it/src/test/scala/com/wavesplatform/it/TransactionsApiSuite.scala
it/src/test/scala/com/wavesplatform/it/transactions/MassTransferTransactionSuite.scala
src/main/scala/scorex/api/http/BroadcastRequest.scala
src/main/scala/scorex/api/http/assets/SignedMassTransferRequest.scala
src/main/scala/scorex/transaction/Proofs.scala
src/main/scala/scorex/transaction/TransactionFactory.scala
src/main/scala/scorex/transaction/TransactionParser.scala
src/main/scala/scorex/transaction/assets/MassTransferTransaction.scala
src/main/scala/scorex/transaction/assets/ScriptTransferTransaction.scala
src/test/scala/com/wavesplatform/TransactionGen.scala
src/test/scala/com/wavesplatform/UtxPoolSpecification.scala
src/test/scala/scorex/transaction/MassTransferTransactionSpecification.scala

Added Version and Proofs fields to MassTransferTransaction

Mass transfer with proofs

---

it/src/test/scala/com/wavesplatform/it/async/TransactionsApiSuite.scala

JIRA: https://wavesplatform.atlassian.net/browse/NODE-494

Added additional checks for MassTransfer reporting test

---

it/src/main/scala/com/wavesplatform/it/api/SyncHttpApi.scala
it/src/test/scala/com/wavesplatform/it/sync/MassTransferTransactionSuite.scala

JIRA: https://wavesplatform.atlassian.net/projects/NODE/issues/NODE-494

Added tests for MassTransfer with alias usage

---

project/Dependencies.scala
src/main/scala/com/wavesplatform/Application.scala
src/main/scala/com/wavesplatform/network/HandshakeHandler.scala
src/main/scala/com/wavesplatform/network/RxExtensionLoader.scala
src/main/scala/com/wavesplatform/network/RxScoreObserver.scala
src/test/scala/com/wavesplatform/network/RxExtensionLoaderSpec.scala
src/test/scala/com/wavesplatform/network/RxScoreObserverSpec.scala

Added new subject to notify about timeout in RxExtensionLoader
Netty version updated

NODE 428: Fix Loading extensions from closed channel

---

it/src/main/scala/com/wavesplatform/it/api/AsyncHttpApi.scala
it/src/main/scala/com/wavesplatform/it/api/SyncHttpApi.scala
it/src/test/scala/com/wavesplatform/it/sync/transactions/CustomFeeTransactionSuite.scala

JIRA: https://wavesplatform.atlassian.net/browse/NODE-567

Added test with custom feeAsset

---

src/test/scala/com/wavesplatform/settings/FeesSettingsSpecification.scala

Changes:
- Added two new tx types to the test
- Replaced default fee values in the test with random ones (because if we override default values with themselves, we don't really test anything)

Fixed unit test failure

---

it/src/main/scala/com/wavesplatform/it/api/AsyncHttpApi.scala
it/src/main/scala/com/wavesplatform/it/api/SyncHttpApi.scala
it/src/test/scala/com/wavesplatform/it/sync/transactions/LeaseStatusTestSuite.scala

JIRA: https://wavesplatform.atlassian.net/browse/NODE-520

NODE-520 Added verification for active leasing status

---

src/main/scala/com/wavesplatform/features/BlockchainFeature.scala
src/main/scala/com/wavesplatform/features/api/ActivationApiRoute.scala
src/main/scala/com/wavesplatform/features/api/FeatureActivationStatus.scala

JIRA: https://wavesplatform.atlassian.net/browse/NODE-622
Sample output after the fix:
```
{
"height" : 295,
"votingInterval" : 10,
"votingThreshold" : 8,
"nextCheck" : 300,
"features" : [ {
"id" : 1,
"description" : "Minimum Generating Balance of 1000 WAVES",
"blockchainStatus" : "ACTIVATED",
"nodeStatus" : "VOTED",
"activationHeight" : 20
}, {
"id" : 2,
"description" : "NG Protocol",
"blockchainStatus" : "ACTIVATED",
"nodeStatus" : "VOTED",
"activationHeight" : 20
}, {
"id" : 3,
"description" : "Mass Transfer Transaction",
"blockchainStatus" : "ACTIVATED",
"nodeStatus" : "IMPLEMENTED",
"activationHeight" : 0
}, {
"id" : 4,
"description" : "Smart Accounts",
"blockchainStatus" : "ACTIVATED",
"nodeStatus" : "IMPLEMENTED",
"activationHeight" : 0
} ]
}
```

NODE-622 Add feature description to /activation/status

---

it/src/test/scala/com/wavesplatform/it/sync/DataTransactionSuite.scala

JIRA: https://wavesplatform.atlassian.net/browse/NODE-627

NODE-627 Dynamic way of fee calculation was added to dtx tests

---

it/src/test/scala/com/wavesplatform/it/sync/DataTransactionSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/MassTransferTransactionSuite.scala

JIRA: https://wavesplatform.atlassian.net/browse/NODE-637

Node 637 masstransfer suite fixes

---

src/test/scala/com/wavesplatform/TransactionGen.scala
src/test/scala/scorex/transaction/DataTransactionSpecification.scala

JIRA: https://wavesplatform.atlassian.net/browse/NODE-633

NODE-633 DataTransactionSpecification fails sometimes

---

it/src/main/resources/template.conf
src/main/scala/com/wavesplatform/features/BlockchainFeature.scala

JIRA: https://wavesplatform.atlassian.net/browse/NODE-640

NODE-640 Hide SmartAccounts feature from voting and REST API

---

it/src/test/scala/com/wavesplatform/it/sync/DataTransactionSuite.scala
src/main/scala/scorex/api/http/AddressApiRoute.scala

JIRA: https://wavesplatform.atlassian.net/browse/NODE-634

NODE-634 Impossible to retrieve data associated with an empty key

---

build.sbt
it/src/main/scala/com/wavesplatform/it/Docker.scala
src/main/resources/application.conf

There is no way to disable Kamon at start. 
So we hide this message coz we know what we are doing :D

NODE-660 Disable AspectJ Weaver missing error

---

src/main/scala/com/wavesplatform/database/LevelDBWriter.scala

Wrong status change of pre-activated feature fixed

NODE-649 Feature preactivation bug

---

src/main/scala/scorex/api/http/leasing/LeaseApiRoute.scala

Also as per discussion with frontend team, both incoming and outgoing leases are returned.

NODE-579: Active Leases performance improvements

---

src/main/scala/com/wavesplatform/state2/diffs/TransferTransactionDiff.scala

[JIRA](https://wavesplatform.atlassian.net/browse/NODE-652)

NODE-652 Disallow smart asset as a fee 

---

it/src/main/scala/com/wavesplatform/it/api/AsyncHttpApi.scala
it/src/main/scala/com/wavesplatform/it/api/SyncHttpApi.scala
it/src/main/scala/com/wavesplatform/it/api/model.scala
it/src/test/scala/com/wavesplatform/it/sync/MinerStateTestSuite.scala

JIRA: https://wavesplatform.atlassian.net/projects/NODE/issues/NODE-620

NODE-620: Node can mine after effective balance increase

---

src/test/scala/com/wavesplatform/state2/diffs/TransferTransactionDiffTest.scala

NODE-652 Dissalow smart asset

---

src/main/scala/com/wavesplatform/database/LevelDBWriter.scala
src/main/scala/com/wavesplatform/features/BlockchainFeature.scala
src/main/scala/com/wavesplatform/state2/diffs/AssetTransactionsDiff.scala
src/main/scala/com/wavesplatform/state2/diffs/TransactionDiffer.scala
src/test/scala/com/wavesplatform/state2/diffs/AssetTransactionsDiffTest.scala

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-581?filter=-1](https://wavesplatform.atlassian.net/browse/NODE-581?filter=-1)

NODE-581 Burn non-owned tokens

---

src/main/scala/scorex/transaction/assets/exchange/Order.scala

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-509](https://wavesplatform.atlassian.net/browse/NODE-509)

NODE-509 Swagger unnecessary fields

---

lang/jvm/src/test/scala/com/wavesplatform/lang/EvaluatorTest.scala
lang/jvm/src/test/scala/com/wavesplatform/lang/ParserTest.scala
lang/shared/src/main/scala/com/wavesplatform/lang/Parser.scala
src/test/scala/com/wavesplatform/state2/diffs/smart/predef/AddressTest.scala

[JRIA: https://wavesplatform.atlassian.net/browse/NODE-623](https://wavesplatform.atlassian.net/browse/NODE-623)

NODE-623 Parser expr fix

---

it/src/main/resources/template.conf
it/src/test/scala/com/wavesplatform/it/sync/BurnTransactionSuite.scala

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-581](https://wavesplatform.atlassian.net/browse/NODE-581)

NODE-581 Burn any tokens

---

it/src/test/scala/com/wavesplatform/it/sync/MinerStateTestSuite.scala

Just to avoid situation with fork a balances for miners were redefined.

NODE-575: Redefined genesis block for MinerStateTestSuite

---

src/main/scala/com/wavesplatform/state2/diffs/AssetTransactionsDiff.scala
src/main/scala/com/wavesplatform/state2/diffs/TransactionDiffer.scala
src/test/scala/com/wavesplatform/state2/diffs/AssetTransactionsDiffTest.scala

Check activation.

---

lang/jvm/src/test/scala/com/wavesplatform/lang/ParserTest.scala
lang/shared/src/main/scala/com/wavesplatform/lang/testing/ScriptGen.scala

Extended CONST_LONG expressions check

---

it/src/test/scala/com/wavesplatform/it/async/activation/ActivationFeatureTestSuite.scala

https://wavesplatform.atlassian.net/browse/NODE-622

check feature description in all statuses

---

lang/js/src/main/scala/com/wavesplatform/lang/WavesContext.scala
lang/js/src/main/scala/com/wavesplatform/lang/impl/Environment.scala
lang/shared/src/main/scala/com/wavesplatform/lang/ctx/impl/WavesContext.scala
lang/shared/src/main/scala/com/wavesplatform/lang/traits/Environment.scala
src/main/scala/scorex/transaction/smart/BlockchainContext.scala

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-641](https://wavesplatform.atlassian.net/browse/NODE-641)

NODE-641 Predef balance functions

---

lang/jvm/src/test/scala/com/wavesplatform/lang/ParserTest.scala
lang/shared/src/main/scala/com/wavesplatform/lang/testing/ScriptGen.scala

Also were removed unnecessary tests

NODE-434 Added gen for block and string expressions

---

lang/jvm/src/test/scala/com/wavesplatform/lang/v1/ScriptComplexityCalculatorTest.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/ScriptComplexityCalculator.scala
src/main/scala/com/wavesplatform/Application.scala
src/main/scala/scorex/api/http/AddressApiRoute.scala
src/main/scala/scorex/api/http/UtilsApiRoute.scala
src/main/scala/scorex/transaction/FeeCalculator.scala
src/main/scala/scorex/transaction/smart/script/ScriptCompiler.scala
src/main/scala/scorex/transaction/smart/script/ScriptRunner.scala
src/test/scala/com/wavesplatform/http/AddressRouteSpec.scala
src/test/scala/com/wavesplatform/http/UtilsRouteSpec.scala
src/test/scala/com/wavesplatform/utx/UtxPoolSpecification.scala
src/test/scala/scorex/transaction/smart/script/ScriptCompilerTest.scala

NODE-603 API: GET script/cost for account

---

src/test/scala/tools/GenesisBlockGenerator.scala

If we comment this [line](https://github.com/wavesplatform/Waves/blob/master/src/test/resources/genesis.example.conf#L8):
```
timestamp: 1500635421931 # Comment to use the current time
```
GenesisBlockGenerator fails with an exception. This PR fixes an issue.

NODE-672 GenesisBlockGenerator should work with an empty timestamp

---

src/main/resources/application.conf
src/main/scala/com/wavesplatform/Application.scala
src/main/scala/com/wavesplatform/settings/FeesSettings.scala
src/main/scala/com/wavesplatform/state/diffs/CommonValidation.scala
src/main/scala/scorex/api/http/AddressApiRoute.scala
src/main/scala/scorex/api/http/UtilsApiRoute.scala
src/main/scala/scorex/api/http/assets/AssetsApiRoute.scala
src/test/scala/com/wavesplatform/http/AddressRouteSpec.scala
src/test/scala/com/wavesplatform/http/UtilsRouteSpec.scala
src/test/scala/com/wavesplatform/settings/FeesSettingsSpecification.scala
src/test/scala/com/wavesplatform/state/diffs/CommonValidationTest.scala
src/test/scala/com/wavesplatform/utx/UtxPoolSpecification.scala
src/test/scala/scorex/api/http/AssetsApiRouteSpec.scala
src/test/scala/scorex/transaction/FeeCalculatorSpecification.scala

NODE-707 Smart token complexity

---

src/main/scala/scorex/api/http/PaymentApiRoute.scala
src/main/scala/scorex/api/http/alias/AliasApiRoute.scala
src/main/scala/scorex/api/http/alias/AliasBroadcastApiRoute.scala
src/main/scala/scorex/api/http/assets/AssetsApiRoute.scala
src/main/scala/scorex/api/http/assets/AssetsBroadcastApiRoute.scala
src/main/scala/scorex/api/http/leasing/LeaseApiRoute.scala
src/main/scala/scorex/api/http/leasing/LeaseBroadcastApiRoute.scala
src/main/scala/scorex/waves/http/WavesApiRoute.scala

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-724](https://wavesplatform.atlassian.net/browse/NODE-724)

NODE-724: Swagger annotations fix

---

lang/shared/src/main/scala/com/wavesplatform/lang/v1/EvaluationContext.scala

Fix lens types inferring in evaluator

Lens Types

---

lang/jvm/src/test/scala/com/wavesplatform/lang/IntegrationTest.scala
lang/jvm/src/test/scala/com/wavesplatform/lang/ParserTest.scala
lang/jvm/src/test/scala/com/wavesplatform/lang/SerdeTest.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/PureContext.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/testing/ScriptGen.scala
src/test/scala/com/wavesplatform/TransactionGen.scala
src/test/scala/com/wavesplatform/state/diffs/smart/predef/CommonFunctionsTest.scala

Bigint without restrictions make some problem.
We will be able start to use Bigint with size restriction and save compatibility with addExact behavior.

addExact using was imlemented now.

---

src/main/scala/com/wavesplatform/database/LevelDBWriter.scala
src/test/scala/com/wavesplatform/state/RollbackSpec.scala

Support rollback sponsorship transaction.

---

lang/jvm/src/test/scala/com/wavesplatform/lang/IntegrationTest.scala
lang/jvm/src/test/scala/com/wavesplatform/lang/ParserTest.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/compiler/CompilerV1.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/compiler/Terms.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/compiler/TypeInferrer.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/PureContext.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/parser/Parser.scala
src/test/scala/com/wavesplatform/TransactionGen.scala
src/test/scala/com/wavesplatform/state/diffs/smart/scenarios/OracleDataTest.scala

case _ : XXX | YYY => ... // Don't create new variable.
case _ => ...  // All other type.

Support new patterns

---

it/src/test/scala/com/wavesplatform/it/sync/AtomicSwapSmartContractSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/MassTransferTransactionSuite.scala

- fee fixed
- unused import deleted

NODE-434 Support of new way of proof identification

---

lang/jvm/src/test/scala/com/wavesplatform/lang/IntegrationTest.scala
lang/jvm/src/test/scala/com/wavesplatform/lang/ParserTest.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/PureContext.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/parser/BinaryOperation.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/parser/Parser.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/parser/UnaryOperation.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/testing/ScriptGen.scala

 NODE-732 Additional operations (unary, comparison for other types, etc)

---

it/src/test/scala/com/wavesplatform/it/sync/LeaseSmartContractsTestSuite.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/testing/ScriptGen.scala

JIRA: https://wavesplatform.atlassian.net/browse/NODE-725
This was actually addressed by NODE-699, this fix just removes a workaround from a test

NODE-725 Proof with empty string cannot be decoded

---

src/main/scala/scorex/api/http/ApiError.scala
src/main/scala/scorex/api/http/UtilsApiRoute.scala

JIRA: https://wavesplatform.atlassian.net/browse/NODE-767
Made the methods return BAD_REQUEST when script does not compile

NODE-767 /utils/script API methods always return HTTP_OK

---

benchmark/src/test/scala/com/wavesplatform/state/StateSyntheticBenchmark.scala
it/src/test/scala/com/wavesplatform/it/async/RollbackSpecSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/AtomicSwapSmartContractSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/LeaseSmartContractsTestSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/MassTransferSmartContractSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/MassTransferTransactionSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/SetScriptTransactionSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/transactions/SponsorshipSuite.scala
lang/js/src/main/scala/JsAPI.scala
lang/jvm/src/test/scala/com/wavesplatform/lang/IntegrationTest.scala
lang/jvm/src/test/scala/com/wavesplatform/lang/ParserTest.scala
lang/jvm/src/test/scala/com/wavesplatform/lang/typechecker/CompilerV1Test.scala
lang/jvm/src/test/scala/com/wavesplatform/lang/typechecker/ErrorTest.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/compiler/CompilerV1.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/compiler/Terms.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/parser/BinaryOperation.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/parser/Expressions.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/parser/Parser.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/parser/UnaryOperation.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/testing/ScriptGen.scala
src/test/scala/com/wavesplatform/state/diffs/AssetTransactionsDiffTest.scala
src/test/scala/com/wavesplatform/state/diffs/smart/performance/SigVerifyPerformanceTest.scala
src/test/scala/com/wavesplatform/state/diffs/smart/predef/package.scala
src/test/scala/com/wavesplatform/state/diffs/smart/scenarios/AddressFromRecipientScenarioTest.scala
src/test/scala/com/wavesplatform/state/diffs/smart/scenarios/HackatonScenartioTest.scala
src/test/scala/com/wavesplatform/state/diffs/smart/scenarios/LazyFieldAccessTest.scala
src/test/scala/com/wavesplatform/state/diffs/smart/scenarios/MultiSig2of3Test.scala
src/test/scala/com/wavesplatform/state/diffs/smart/scenarios/OnlyTransferIsAllowedTest.scala
src/test/scala/com/wavesplatform/state/diffs/smart/scenarios/OracleDataTest.scala

NODE-742 Parsing of invalid expressions

---

src/main/scala/com/wavesplatform/state/diffs/AssetTransactionsDiff.scala
src/main/scala/scorex/transaction/assets/BurnTransaction.scala
src/main/scala/scorex/transaction/assets/BurnTransactionV1.scala
src/main/scala/scorex/transaction/assets/BurnTransactionV2.scala
src/main/scala/scorex/transaction/smart/RealTransactionWrapper.scala
src/test/scala/com/wavesplatform/http/AssetsBroadcastRouteSpec.scala
src/test/scala/com/wavesplatform/state/diffs/AssetTransactionsDiffTest.scala
src/test/scala/scorex/transaction/BurnTransactionSpecification.scala

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-765](https://wavesplatform.atlassian.net/browse/NODE-765)

NODE-765: Fix burn transaction field naming inconsistency

---

lang/jvm/src/test/scala/com/wavesplatform/lang/EvaluatorV1Test.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/LazyVal.scala
src/main/scala/scorex/transaction/smart/Verifier.scala

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-779](https://wavesplatform.atlassian.net/browse/NODE-779)

NODE-779: Flag for evaluation status added

---

benchmark/src/test/scala/com/wavesplatform/lang/v1/LangSerdeBenchmark.scala
benchmark/src/test/scala/com/wavesplatform/state/StateSyntheticBenchmark.scala
project/plugins.sbt
src/test/scala/com/wavesplatform/http/AssetsBroadcastRouteSpec.scala

* LangSerdeBenchmark: a compaction before deserialization;
* StateSyntheticBenchmark: fixed fees;
* Typos.

NODE-729 Fix benchmarks

---

lang/jvm/src/test/scala/com/wavesplatform/lang/EvaluatorV1Test.scala
lang/jvm/src/test/scala/com/wavesplatform/lang/IntegrationTest.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/PureContext.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/parser/BinaryOperation.scala

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-795](https://wavesplatform.atlassian.net/browse/NODE-795)

NODE-795 Additional operators

---

lang/jvm/src/test/scala/com/wavesplatform/lang/IntegrationTest.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/compiler/CompilerV1.scala

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-802](https://wavesplatform.atlassian.net/browse/NODE-802)

NODE-802: Fix patmat block error

---

lang/jvm/src/test/scala/com/wavesplatform/lang/ParserTest.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/parser/Parser.scala

NODE-744 Comments in smart contracts

---

lang/jvm/src/test/scala/com/wavesplatform/lang/Common.scala
lang/jvm/src/test/scala/com/wavesplatform/lang/EvaluatorV1Test.scala
lang/jvm/src/test/scala/com/wavesplatform/lang/EvaluattorV1CaseObjField.scala
lang/jvm/src/test/scala/com/wavesplatform/lang/v1/ScriptEstimatorTest.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/EvaluatorV1.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/Obj.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/EnvironmentFunctions.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/waves/Bindings.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/waves/WavesContext.scala
src/test/scala/com/wavesplatform/state/diffs/smart/scenarios/AddressFromRecipientScenarioTest.scala

NODE-789-remove-types-from-objects-fields

---

lang/jvm/src/test/scala/com/wavesplatform/lang/Common.scala
lang/jvm/src/test/scala/com/wavesplatform/lang/EvaluatorV1Test.scala
lang/jvm/src/test/scala/com/wavesplatform/lang/TypeInferrerTest.scala
lang/jvm/src/test/scala/com/wavesplatform/lang/typechecker/CompilerV1Test.scala
lang/jvm/src/test/scala/com/wavesplatform/lang/typechecker/package.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/compiler/CompilationError.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/compiler/CompilerContext.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/compiler/CompilerV1.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/compiler/Terms.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/compiler/TypeInferrer.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/compiler/Types.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/Obj.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/PredefCaseType.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/PredefFunction.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/CryptoContext.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/PureContext.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/waves/Types.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/waves/WavesContext.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/testing/TypedScriptGen.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/traits/DataType.scala

TYPES move from Terms to separate module.

NODE-789-split-terms-and-types

---

build.sbt
src/main/scala/com/wavesplatform/features/BlockchainFeature.scala
src/main/scala/com/wavesplatform/network/HandshakeHandler.scala

Increased network compatible version to 0.13.x
Increased fallback version to 0.14.0

SmartAccounts are back

---

src/main/scala/scorex/api/http/assets/AssetsBroadcastApiRoute.scala

s/path("reissue")/path("sponsor")/

NODE-827-fix

---

src/main/scala/scorex/transaction/smart/RealTransactionWrapper.scala

JIRA: https://wavesplatform.atlassian.net/browse/NODE-835
Fixed a typo in RealTransactionWrapper: asset ID was passed as asset name

NODE-835 IssueTransaction.name field is wired to ID

---

lang/jvm/src/test/scala/com/wavesplatform/lang/ParserTest.scala
lang/jvm/src/test/scala/com/wavesplatform/lang/compiler/CompilerV1Test.scala
lang/jvm/src/test/scala/com/wavesplatform/lang/compiler/ErrorTest.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/compiler/CompilerV1.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/parser/BinaryOperation.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/parser/Expressions.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/parser/Parser.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/parser/UnaryOperation.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/testing/ScriptGen.scala

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-813](https://wavesplatform.atlassian.net/browse/NODE-813)

NODE-813 Expressions position

---

lang/jvm/src/test/scala/com/wavesplatform/lang/IntegrationTest.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/compiler/CompilerV1.scala

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-832](https://wavesplatform.atlassian.net/browse/NODE-832)

NODE-832: CompilerV1 checks script return type

---

it/src/test/scala/com/wavesplatform/it/sync/transactions/BurnTransactionV1Suite.scala
src/main/scala/com/wavesplatform/database/LevelDBWriter.scala

NODE-842: Combined AssetInfo stored in state

---

benchmark/src/test/scala/com/wavesplatform/lang/v1/EnvironmentFunctionsBenchmark.scala
benchmark/src/test/scala/com/wavesplatform/state/WavesEnvironmentBenchmark.scala
lang/js/src/main/scala/com/wavesplatform/lang/WavesContext.scala
lang/js/src/main/scala/com/wavesplatform/lang/impl/Environment.scala
lang/jvm/src/test/scala/com/wavesplatform/lang/Common.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/EnvironmentFunctions.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/waves/WavesContext.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/traits/Environment.scala
src/main/scala/com/wavesplatform/state/package.scala
src/main/scala/scorex/transaction/smart/WavesEnvironment.scala

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-739](https://wavesplatform.atlassian.net/browse/NODE-739)

NODE-739: Get data by address or alias

---

lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/Obj.scala
src/main/scala/scorex/api/http/ApiError.scala

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-811](https://wavesplatform.atlassian.net/browse/NODE-811)

NODE-811: ScriptError API response

---

lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/waves/WavesContext.scala

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-739](https://wavesplatform.atlassian.net/browse/NODE-739)

NODE-739: Fix getDataF input type

---

src/main/scala/com/wavesplatform/database/LevelDBWriter.scala
src/test/scala/com/wavesplatform/state/RollbackSpec.scala

Fix order of returns doRollback.

NODE-893-replay-rollbacked-blocks-order

---

benchmark/src/main/scala/com/wavesplatform/state/ExtractInfo.scala
benchmark/src/test/scala/com/wavesplatform/lang/v1/ScriptEstimatorBenchmark.scala
lang/jvm/src/test/scala/com/wavesplatform/lang/TypeInferrerTest.scala
lang/jvm/src/test/scala/com/wavesplatform/lang/v1/ScriptEstimatorTest.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/ScriptEstimator.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/EvaluationContext.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/NativeFunction.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/PureContext.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/waves/WavesContext.scala
src/main/scala/com/wavesplatform/utils/package.scala
src/main/scala/scorex/transaction/smart/script/ScriptCompiler.scala
src/main/scala/scorex/transaction/smart/script/v1/ScriptV1.scala
src/test/scala/com/wavesplatform/utils/UtilsSpecification.scala

JIRA: https://wavesplatform.atlassian.net/browse/NODE-895
Costs are calculated for all user functions at once in
com/wavesplatform/utils/package.scala

NODE-895 User functions cost to be calculated not hardcoded

---

it/src/main/resources/template.conf
it/src/main/scala/com/wavesplatform/it/api/SyncHttpApi.scala
it/src/test/scala/com/wavesplatform/it/sync/PoSSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/RollbackSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/smartcontract/AtomicSwapSmartContractSuite.scala
src/main/resources/application.conf
src/main/scala/com/wavesplatform/settings/MinerSettings.scala
src/main/scala/com/wavesplatform/settings/WavesSettings.scala

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-906](https://wavesplatform.atlassian.net/browse/NODE-906)

NODE-906: Generation offset

---

src/main/scala/com/wavesplatform/state/diffs/BalanceDiffValidation.scala
src/test/scala/com/wavesplatform/state/diffs/BalanceDiffValidationTest.scala

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-899](https://wavesplatform.atlassian.net/browse/NODE-899)

NODE-899: Wrong error message

---

src/main/scala/com/wavesplatform/network/PeerDatabaseImpl.scala

Additional checks in PeerDatabaseImpl.addCandidate()

NODE-834 Node connected to itself, second take

---

src/main/scala/com/wavesplatform/database/LevelDBWriter.scala
src/test/scala/com/wavesplatform/history/Domain.scala
src/test/scala/com/wavesplatform/state/RollbackSpec.scala

Clean transactions by address store while rollback.

NODE-897-duplicate-transactions-after-rollback

---

src/main/resources/application.conf
src/main/scala/com/wavesplatform/matcher/MatcherSettings.scala
src/main/scala/com/wavesplatform/matcher/api/MatcherApiRoute.scala
src/main/scala/com/wavesplatform/matcher/market/MatcherActor.scala
src/test/scala/com/wavesplatform/matcher/MatcherTestData.scala
src/test/scala/com/wavesplatform/matcher/market/MatcherActorSpecification.scala
src/test/scala/com/wavesplatform/settings/MatcherSettingsSpecification.scala
waves-devnet.conf
waves-testnet.conf

Add API to get configuration parameter price-assets.
Remove assets-pairs support.

NODE-931-price-assets-api

---

src/test/scala/com/wavesplatform/db/ScriptCacheTest.scala
src/test/scala/com/wavesplatform/state/diffs/SponsorshipDiffTest.scala

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-912](https://wavesplatform.atlassian.net/browse/NODE-912)

NODE-912: Script cache test

---

it/src/main/scala/com/wavesplatform/it/api/AsyncHttpApi.scala
it/src/main/scala/com/wavesplatform/it/api/SyncHttpApi.scala
it/src/test/scala/com/wavesplatform/it/sync/smartcontract/AtomicSwapSmartContractSuite.scala

See the reasons in the AtomicSwapSmartContractSuite's source.

NODE-933 AtomicSwapSmartContractSuite works with one node

---

src/main/scala/com/wavesplatform/state/diffs/BalanceDiffValidation.scala

Reverts wavesplatform/Waves#1296

Revert "NODE-899 Remove unnecessary check of leasing"

---

src/main/scala/com/wavesplatform/matcher/Matcher.scala
src/main/scala/com/wavesplatform/matcher/market/MatcherActor.scala
src/main/scala/com/wavesplatform/matcher/market/OrderBookActor.scala

NODE-934 Saving OrderBookActor snapshots on shutdown

---

src/main/resources/application.conf
src/main/scala/com/wavesplatform/matcher/market/MatcherActor.scala
src/main/scala/com/wavesplatform/matcher/model/EventSerializers.scala

NODE-953 Recover order books in parallel

---

src/main/scala/com/wavesplatform/matcher/market/OrderHistoryActor.scala
src/main/scala/com/wavesplatform/matcher/model/MatcherModel.scala
src/main/scala/com/wavesplatform/matcher/model/OrderHistory.scala
src/main/scala/com/wavesplatform/matcher/model/OrderInfo.scala
src/main/scala/com/wavesplatform/matcher/model/OrderValidator.scala
src/main/scala/scorex/transaction/assets/exchange/Validation.scala
src/test/scala/com/wavesplatform/matcher/model/OrderHistorySpecification.scala

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-954](https://wavesplatform.atlassian.net/browse/NODE-954)

Node 954 Order filled amount

---

it/src/test/scala/com/wavesplatform/it/sync/package.scala
it/src/test/scala/com/wavesplatform/it/sync/transactions/ExchangeTransactionSuite.scala
src/main/scala/com/wavesplatform/state/diffs/ExchangeTransactionDiff.scala

JIRA: Exchange Tx. No check for asset existance
Added a check to ExchangeTransactionDiff

NODE-990 Exchange Tx. No check for asset existance

---

it/src/main/scala/com/wavesplatform/it/api/AsyncMatcherHttpApi.scala
it/src/main/scala/com/wavesplatform/it/api/SyncMatcherHttpApi.scala
it/src/main/scala/com/wavesplatform/it/api/model.scala
it/src/test/scala/com/wavesplatform/it/sync/matcher/MatcherTestSuite.scala
src/main/scala/com/wavesplatform/matcher/api/MatcherApiRoute.scala
src/main/scala/com/wavesplatform/matcher/market/MatcherActor.scala
src/main/scala/com/wavesplatform/matcher/market/OrderBookActor.scala

JIRA: https://wavesplatform.atlassian.net/browse/NODE-960
Redesigned API: removed asset info, added last trade side (buy/sell), retained last price, best bid & ask

NODE-960 Matcher market status method -- API redesign

---

src/main/scala/com/wavesplatform/matcher/api/MatcherApiRoute.scala

JIRA: https://wavesplatform.atlassian.net/browse/NODE-960
Corrected Swagger annotations

NODE-960 Matcher API: matcher/orderbook/... method

---

it/src/main/scala/com/wavesplatform/it/api/SyncHttpApi.scala
src/main/scala/com/wavesplatform/Application.scala
src/main/scala/com/wavesplatform/api/http/ApiRoute.scala
src/main/scala/com/wavesplatform/api/http/TransactionsApiRoute.scala
src/main/scala/com/wavesplatform/http/DebugApiRoute.scala
src/main/scala/com/wavesplatform/transaction/TransactionFactory.scala
src/test/scala/com/wavesplatform/http/DebugApiRouteSpec.scala

JIRA: https://wavesplatform.atlassian.net/browse/NODE-1049
URL: `/debug/validate` (protected with API key)
Example response:
```
{
"valid": false,
"error": "invalid signature",
"validationTime": 1.254
}
```

NODE-1049 API method to get validation time of the script

---

it/src/main/scala/com/wavesplatform/it/api/model.scala
it/src/test/scala/com/wavesplatform/it/sync/matcher/MatcherTestSuite.scala
src/main/scala/com/wavesplatform/matcher/market/OrderBookActor.scala

JIRA: https://wavesplatform.atlassian.net/browse/NODE-960

NODE-960 Added bidAmount / askAmount

---

src/main/scala/com/wavesplatform/matcher/market/MatcherActor.scala

JIRA: https://wavesplatform.atlassian.net/browse/NODE-1047
Changes:
- MatcherActor no longer waits for reply from child actors, because they might crash while taking snapshots. Instead, it watches for children termination
- Handled the case where there are no child actors

NODE-1047 Matcher doesn't stop on SIGTERM

---

it/src/main/scala/com/wavesplatform/it/api/AsyncMatcherHttpApi.scala
it/src/main/scala/com/wavesplatform/it/api/SyncHttpApi.scala
it/src/main/scala/com/wavesplatform/it/api/SyncMatcherHttpApi.scala
it/src/test/scala/com/wavesplatform/it/sync/matcher/CancellOrderTestSuite.scala
src/main/scala/com/wavesplatform/matcher/market/OrderHistoryActor.scala

Node 956 cancel order test

---

it/src/test/scala/com/wavesplatform/it/sync/smartcontract/ScriptExecutionErrorSuite.scala
src/main/scala/com/wavesplatform/matcher/market/MatcherActor.scala
src/main/scala/com/wavesplatform/transaction/smart/Verifier.scala

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-1065](https://wavesplatform.atlassian.net/browse/NODE-1065)

NODE-1065: Correct error message

---

benchmark/src/test/scala/com/wavesplatform/lang/v1/ScriptEvaluatorBenchmark.scala
it/src/test/scala/com/wavesplatform/it/sync/smartcontract/BigString.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/PureContext.scala

Set string size limit to Short.MaxValue
Remove MinStep posibility.

NODE-1076-simpify-constraint

---

src/main/scala/com/wavesplatform/state/diffs/CommonValidation.scala

JIRA: https://wavesplatform.atlassian.net/browse/NODE-1079

NODE-1079 Increase SetScript fee from 0.001 to 0.01 WAVES

---

it/src/test/scala/com/wavesplatform/it/sync/matcher/MatcherRestartTestSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/matcher/RoundingIssuesTestSuite.scala
src/main/scala/com/wavesplatform/matcher/market/OrderBookActor.scala
src/main/scala/com/wavesplatform/matcher/model/ExchangeTransactionCreator.scala
src/main/scala/com/wavesplatform/matcher/model/OrderHistory.scala

has PartiallyFilled, but should have Filled

NODE-1086 An order can have a wrong status after execution

---

src/main/scala/com/wavesplatform/matcher/MigrationTool.scala
src/main/scala/com/wavesplatform/matcher/model/OrderInfo.scala

* Wrong remainingFee;
* Fixed OrderInfo.totalSpend (was remainingSpend in case of unsafeTotalSpend=None).

Fixes for migration tool

---

src/main/scala/com/wavesplatform/matcher/Matcher.scala
src/main/scala/com/wavesplatform/matcher/api/MatcherApiRoute.scala

Check order sender scripted in API route.

NODE-1058-check-scripted-in-route

---

src/main/scala/com/wavesplatform/state/diffs/CommonValidation.scala

Place actual height to error message about duplicate transactions.

NODE-1049-fix-message

---

it/src/test/scala/com/wavesplatform/it/sync/matcher/MatcherTestSuite.scala
src/main/scala/com/wavesplatform/matcher/market/MatcherActor.scala
src/main/scala/com/wavesplatform/matcher/market/OrderBookActor.scala

Store last placed macthed order.

NODE-960-fix-last-order-info

---

src/test/scala/com/wavesplatform/state/diffs/smart/scenarios/ScriptedSponsorTest.scala

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-1122](https://wavesplatform.atlassian.net/browse/NODE-1122)

NODE-1122: Additional tests for sponsorship

---

src/main/scala/com/wavesplatform/api/http/UtilsApiRoute.scala

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-1056](https://wavesplatform.atlassian.net/browse/NODE-1056)

NODE-1143: Fix UtilsApiRoute swagger annotations

---

it/src/main/scala/com/wavesplatform/it/api/AsyncHttpApi.scala
src/main/scala/com/wavesplatform/api/http/ConnectReq.scala
src/main/scala/com/wavesplatform/api/http/PeersApiRoute.scala

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-1141](https://wavesplatform.atlassian.net/browse/NODE-1141)

NODE-1141: PeersApiRoute swagger fixed

---

it/src/test/scala/com/wavesplatform/it/sync/matcher/OrdersFromScriptedAccTestSuite.scala
src/main/scala/com/wavesplatform/features/BlockchainFeature.scala
src/main/scala/com/wavesplatform/matcher/Matcher.scala
src/main/scala/com/wavesplatform/matcher/api/MatcherApiRoute.scala
src/main/scala/com/wavesplatform/state/diffs/CommonValidation.scala
src/main/scala/com/wavesplatform/state/diffs/ExchangeTransactionDiff.scala
src/test/scala/com/wavesplatform/state/diffs/ExchangeTransactionDiffTest.scala
src/test/scala/com/wavesplatform/state/diffs/smart/scenarios/ScriptedSponsorTest.scala

JIRA: https://wavesplatform.atlassian.net/browse/NODE-1160
Trading from Smart Accounts is tied to SmartAccountTrading feature

NODE-1160 Enable trading from Smart Accounts

---

src/main/scala/com/wavesplatform/api/http/assets/AssetsApiRoute.scala
src/main/scala/com/wavesplatform/serialization/BytesSerializable.scala
src/main/scala/com/wavesplatform/transaction/Signed.scala
src/main/scala/com/wavesplatform/transaction/assets/exchange/AssetPair.scala
src/main/scala/com/wavesplatform/transaction/assets/exchange/Order.scala
src/main/scala/com/wavesplatform/transaction/assets/exchange/OrderType.scala
src/main/scala/com/wavesplatform/transaction/assets/exchange/OrderV1.scala
src/main/scala/com/wavesplatform/transaction/assets/exchange/OrderV2.scala

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-1137](https://wavesplatform.atlassian.net/browse/NODE-1137)

NODE-1137: AssetsApiRoute swagger annotations

---

it/src/test/scala/com/wavesplatform/it/sync/UtxSuite.scala
src/main/scala/com/wavesplatform/utx/UtxPoolImpl.scala

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-546](https://wavesplatform.atlassian.net/browse/NODE-546)

NODE-546: Utx cleanup

---

build.sbt
lang/jvm/src/main/java/com/wavesplatform/lang/Lang.java
lang/jvm/src/main/scala/com/wavesplatform/lang/JavaAdapter.scala
project/plugins.sbt

JIRA: https://wavesplatform.atlassian.net/browse/NODE-1152
Maven page: https://mvnrepository.com/artifact/com.wavesplatform/lang

NODE-1152 Publish RIDE compiler as Maven artefact

---

it/src/main/scala/com/wavesplatform/it/api/AsyncMatcherHttpApi.scala
it/src/main/scala/com/wavesplatform/it/api/SyncMatcherHttpApi.scala
it/src/test/scala/com/wavesplatform/it/sync/matcher/CancelOrderTestSuite.scala

https://wavesplatform.atlassian.net/browse/NODE-1157

NODE-1157: Test on order delete

---

lang/js/src/main/scala/JsAPI.scala
lang/jvm/src/test/scala/com/wavesplatform/lang/Common.scala
lang/jvm/src/test/scala/com/wavesplatform/lang/EvaluatorV1Test.scala
lang/jvm/src/test/scala/com/wavesplatform/lang/IntegrationTest.scala
lang/jvm/src/test/scala/com/wavesplatform/lang/compiler/CompilerV1Test.scala
lang/jvm/src/test/scala/com/wavesplatform/lang/compiler/package.scala
lang/jvm/src/test/scala/com/wavesplatform/lang/v1/ScriptEstimatorTest.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/CTX.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/compiler/CompilerContext.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/compiler/CompilerV1.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/NativeFunction.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/CryptoContext.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/PureContext.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/waves/WavesContext.scala
src/main/scala/com/wavesplatform/matcher/smart/MatcherContext.scala
src/test/scala/com/wavesplatform/utils/UtilsSpecification.scala

Add docstring to RADE functions.

NODE-1145-docstrings

---

lang/jvm/src/main/scala/com/wavesplatform/lang/Global.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/BaseGlobal.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/CryptoContext.scala
src/test/scala/com/wavesplatform/state/diffs/smart/predef/ContextFunctionsTest.scala
src/test/scala/com/wavesplatform/state/diffs/smart/predef/TransactionBindingsTest.scala

JIRA: https://wavesplatform.atlassian.net/browse/NODE-1202
Put a 32k limit on byte vectors going into base64Encode/Decode

NODE-1202 Amplification in Smart Account

---

lang/jvm/src/main/scala/com/wavesplatform/lang/Global.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/BaseGlobal.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/CryptoContext.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/parser/Parser.scala
src/main/scala/com/wavesplatform/transaction/smart/script/ScriptCompiler.scala
src/test/scala/com/wavesplatform/state/diffs/smart/predef/ContextFunctionsTest.scala
src/test/scala/com/wavesplatform/state/diffs/smart/predef/TransactionBindingsTest.scala

Merged fixes for stack overflow in script parser and base64 amplification

Merged 0.14.6 fixes

---

lang/jvm/src/test/scala/com/wavesplatform/lang/SerdeTest.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/Serde.scala

Handle invalid bytes array size.

FixOutOfMemoryInSerde

---

src/main/scala/com/wavesplatform/matcher/api/DBUtils.scala
src/test/scala/com/wavesplatform/matcher/market/OrderValidatorSpecification.scala
src/test/scala/com/wavesplatform/matcher/model/OrderHistorySpecification.scala

Also we return all active order in pairs, even they count exceeds the limit.

DEX-123 Additional unit tests for indexes

---

it/src/test/scala/com/wavesplatform/it/sync/AssetDistributionSuite.scala
src/main/resources/application.conf
src/main/scala/com/wavesplatform/api/http/TransactionsApiRoute.scala
src/main/scala/com/wavesplatform/api/http/assets/AssetsApiRoute.scala
src/main/scala/com/wavesplatform/api/http/package.scala
src/main/scala/com/wavesplatform/database/LevelDBWriter.scala
src/main/scala/com/wavesplatform/settings/RestAPISettings.scala
src/main/scala/com/wavesplatform/state/Blockchain.scala
src/main/scala/com/wavesplatform/state/BlockchainUpdaterImpl.scala
src/main/scala/com/wavesplatform/state/reader/CompositeBlockchain.scala
src/test/scala/com/wavesplatform/http/RestAPISettingsHelper.scala
src/test/scala/com/wavesplatform/http/TransactionsRouteSpec.scala
src/test/scala/com/wavesplatform/settings/RestAPISettingsSpecification.scala

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-1189](https://wavesplatform.atlassian.net/browse/NODE-1189)

NODE-1189: Balance distribution api method

---

src/main/scala/com/wavesplatform/matcher/MatcherSnapshotStore.scala
src/main/scala/com/wavesplatform/matcher/MatcherTool.scala
src/main/scala/com/wavesplatform/matcher/api/DBUtils.scala
src/main/scala/com/wavesplatform/matcher/api/MatcherApiRoute.scala
src/main/scala/com/wavesplatform/matcher/market/OrderBookActor.scala
src/test/scala/com/wavesplatform/matcher/model/OrderHistorySpecification.scala

* Fixed an issue with wrong order of applied events at start;
* Fixed an issue with multiple saves;
* Metrics for snapshot creation and serialization;
* Unit tests for wrong order of events;
* Improved logging.

DEX-127 Snapshot fixes

---

benchmark/build.sbt
it/src/main/scala/com/wavesplatform/it/MatcherNode.scala
it/src/test/scala/com/wavesplatform/it/sync/matcher/smartcontracts/OrdersFromScriptedAccTestSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/matcher/smartcontracts/ProofAndAssetPairTestSuite.scala
src/main/scala/com/wavesplatform/matcher/model/OrderValidator.scala
src/test/scala/com/wavesplatform/matcher/market/OrderValidatorSpecification.scala

* Removed unnecessary check for order by matcher's account;
* New unit tests;
* Un-ignored tests in OrdersFromScriptedAccTestSuite;
* Some code improvements (removed nulls and unnecessary waitForHeightArise in tests).

DEX-129 Can not place an order with multiple proofs

---

src/main/scala/com/wavesplatform/transaction/smart/Verifier.scala
src/test/scala/com/wavesplatform/state/diffs/ExchangeTransactionDiffTest.scala

Special checks for ExchangeTransactionV1.

NODE-1228-check-scripted-orderv1

---

it/src/main/scala/com/wavesplatform/it/api/AsyncMatcherHttpApi.scala
it/src/main/scala/com/wavesplatform/it/api/SyncHttpApi.scala
it/src/main/scala/com/wavesplatform/it/api/SyncMatcherHttpApi.scala
it/src/test/scala/com/wavesplatform/it/sync/matcher/CancelOrderTestSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/matcher/MatcherTestSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/matcher/OrderBookTestSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/matcher/RoundingIssuesTestSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/matcher/SeveralPartialOrdersTestSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/matcher/TradeBalanceAndRoundingTestSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/matcher/TradersTestSuite.scala
src/main/scala/com/wavesplatform/matcher/Matcher.scala
src/main/scala/com/wavesplatform/matcher/api/MatcherApiRoute.scala
src/main/scala/com/wavesplatform/matcher/api/MatcherResponse.scala
src/main/scala/com/wavesplatform/matcher/market/MatcherActor.scala
src/main/scala/com/wavesplatform/matcher/market/OrderBookActor.scala
src/test/scala/com/wavesplatform/matcher/market/MatcherActorSpecification.scala
src/test/scala/com/wavesplatform/matcher/market/OrderBookActorSpecification.scala

* OrderBookActor sends Created when starting;
* MatcherActor: orderBookActorProps, new handling for order books creation and termination;
* MatcherActorSpecification completely reworked, added new tests.

DEX-145 Respond with 503 error if an order book is down

---

it/src/test/scala/com/wavesplatform/it/sync/matcher/config/MatcherDefaultConfig.scala
it/src/test/scala/com/wavesplatform/it/sync/matcher/config/MatcherPriceAssetConfig.scala
src/main/scala/com/wavesplatform/matcher/Matcher.scala
src/main/scala/com/wavesplatform/matcher/api/MatcherApiRoute.scala
src/main/scala/com/wavesplatform/matcher/market/OrderHistoryActor.scala
src/main/scala/com/wavesplatform/matcher/model/MatcherModel.scala

* Fallback and dirty solution for issue;
* Graceful stop for OrderHistoryActor;
* Better responses on cancelling orders' requests.

DEX-146 Can't cancel an order

---

it/src/test/scala/com/wavesplatform/it/sync/smartcontract/ExchangeTransactionSuite.scala
src/main/scala/com/wavesplatform/api/http/assets/SignedExchangeRequest.scala

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-1241](https://wavesplatform.atlassian.net/browse/NODE-1241)

NODE-1241: Fix order casting

---

it/src/test/scala/com/wavesplatform/it/sync/CustomFeeTransactionSuite.scala
src/main/scala/com/wavesplatform/state/BlockchainUpdaterImpl.scala

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-1226](https://wavesplatform.atlassian.net/browse/NODE-1226)

NODE-1226: Scripted account fee bug

---

src/main/scala/com/wavesplatform/Application.scala
src/main/scala/com/wavesplatform/api/http/alias/AliasApiRoute.scala
src/main/scala/com/wavesplatform/api/http/alias/AliasBroadcastApiRoute.scala
src/main/scala/com/wavesplatform/api/http/assets/AssetsApiRoute.scala
src/main/scala/com/wavesplatform/api/http/assets/AssetsBroadcastApiRoute.scala
src/main/scala/com/wavesplatform/api/http/leasing/LeaseApiRoute.scala
src/main/scala/com/wavesplatform/api/http/leasing/LeaseBroadcastApiRoute.scala

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-1231](https://wavesplatform.atlassian.net/browse/NODE-1231)

NODE-1158: Obsolete api routes hidden from swagger

---

it/src/test/scala/com/wavesplatform/it/sync/transactions/SignAndBroadcastApiSuite.scala
src/main/scala/com/wavesplatform/api/http/assets/SignedBurnV2Request.scala
src/main/scala/com/wavesplatform/api/http/assets/SignedExchangeRequestV2.scala
src/main/scala/com/wavesplatform/api/http/assets/SignedIssueV2Request.scala
src/main/scala/com/wavesplatform/api/http/assets/SignedMassTransferRequest.scala
src/main/scala/com/wavesplatform/api/http/assets/SignedReissueV2Request.scala
src/main/scala/com/wavesplatform/api/http/assets/SignedSetAssetScriptRequest.scala
src/main/scala/com/wavesplatform/api/http/assets/SignedSetScriptRequest.scala
src/main/scala/com/wavesplatform/api/http/assets/SignedTransferV2Request.scala
src/main/scala/com/wavesplatform/api/http/assets/package.scala

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-1276](https://wavesplatform.atlassian.net/browse/NODE-1276)

NODE-1276: treat null in json as empty proof

---

src/main/resources/application.conf
src/main/scala/com/wavesplatform/matcher/MatcherSettings.scala
src/main/scala/com/wavesplatform/matcher/MatcherSnapshotStore.scala
src/main/scala/com/wavesplatform/matcher/MatcherTool.scala
src/main/scala/com/wavesplatform/matcher/api/MatcherApiRoute.scala
src/main/scala/com/wavesplatform/matcher/market/OrderBookActor.scala
src/test/scala/com/wavesplatform/settings/MatcherSettingsSpecification.scala

* Optional making snapshots at start;
* MatcherTool: dumping orders and order books;
* MatcherApiRoute.forceCancelOrder ability to fix the issue by admin's method.

DEX-148 An order present in order book, but absent in order history

---

it/src/test/scala/com/wavesplatform/it/sync/transactions/SetAssetScriptTransactionSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/transactions/SignAndBroadcastApiSuite.scala
src/main/scala/com/wavesplatform/state/diffs/AssetTransactionsDiff.scala
src/main/scala/com/wavesplatform/state/diffs/CommonValidation.scala

This is a follow up for https://wavesplatform.atlassian.net/browse/NODE-1240
I'm making SetAssetScript error messages hopefully more comprehensible to a casual user

NODE-1240 Reworded SetAssetScript error messages

---

lang/js/src/main/scala/JsAPI.scala
lang/js/src/main/scala/com/wavesplatform/lang/WavesContext.scala
lang/js/src/main/scala/com/wavesplatform/lang/impl/Environment.scala

Fix langJS/fullOptJS
Еще требуется добавить эту задачу в checkPR и сделать тесты для JS.

NODE-1260-fix-compilation

---

it/src/main/scala/com/wavesplatform/it/Node.scala
it/src/main/scala/com/wavesplatform/it/api/AsyncMatcherHttpApi.scala
it/src/main/scala/com/wavesplatform/it/api/SyncMatcherHttpApi.scala
it/src/test/scala/com/wavesplatform/it/sync/MicroblocksSponsoredFeeTestSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/matcher/CancelOrderTestSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/matcher/MatcherMassOrdersTestSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/matcher/MatcherMigrationTestSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/matcher/MatcherRestartTestSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/matcher/MatcherTestSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/matcher/MatcherTickerTestSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/matcher/OrderBookTestSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/matcher/RestOrderLimitTestSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/matcher/TradeBalanceAndRoundingTestSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/matcher/smartcontracts/OrderTypeTestSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/matcher/smartcontracts/OrdersFromScriptedAccTestSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/matcher/smartcontracts/ProofAndAssetPairTestSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/package.scala
it/src/test/scala/com/wavesplatform/it/sync/smartcontract/ExchangeTransactionSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/transactions/SponsorshipSuite.scala
src/main/scala/com/wavesplatform/matcher/Matcher.scala
src/main/scala/com/wavesplatform/matcher/model/ExchangeTransactionCreator.scala
src/main/scala/com/wavesplatform/matcher/model/OrderValidator.scala
src/main/scala/com/wavesplatform/state/Diff.scala
src/main/scala/com/wavesplatform/state/diffs/CommonValidation.scala
src/test/scala/com/wavesplatform/matcher/market/MatcherActorSpecification.scala
src/test/scala/com/wavesplatform/matcher/market/OrderBookActorSpecification.scala
src/test/scala/com/wavesplatform/state/diffs/ExchangeTransactionDiffTest.scala
src/test/scala/com/wavesplatform/state/diffs/smart/scenarios/ScriptedSponsorTest.scala

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-1280](https://wavesplatform.atlassian.net/browse/NODE-1280)

NODE-1280: Fix fee calculation for scripted exchange tx

---

it/src/main/scala/com/wavesplatform/it/api/AsyncHttpApi.scala
it/src/main/scala/com/wavesplatform/it/api/AsyncMatcherHttpApi.scala
it/src/main/scala/com/wavesplatform/it/api/SyncHttpApi.scala
it/src/main/scala/com/wavesplatform/it/api/SyncMatcherHttpApi.scala
it/src/main/scala/com/wavesplatform/it/api/model.scala
it/src/main/scala/com/wavesplatform/it/transactions/BaseTransactionSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/CustomFeeTransactionSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/matcher/BlacklistedTradingTestSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/matcher/CancelOrderTestSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/matcher/MatcherMassOrdersTestSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/matcher/MatcherRestartTestSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/matcher/MatcherTestSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/matcher/MatcherTickerTestSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/matcher/OrderBookTestSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/matcher/OrdersFromScriptedAccTestSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/matcher/RestOrderLimitTestSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/matcher/RoundingIssuesTestSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/matcher/SeveralPartialOrdersTestSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/matcher/TradeBalanceAndRoundingTestSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/matcher/TradersTestSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/matcher/TradingMarketsTestSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/matcher/config/MatcherDefaultConfig.scala
it/src/test/scala/com/wavesplatform/it/sync/matcher/config/MatcherPriceAssetConfig.scala
it/src/test/scala/com/wavesplatform/it/sync/package.scala
it/src/test/scala/com/wavesplatform/it/sync/transactions/BurnTransactionSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/transactions/SignAndBroadcastApiSuite.scala

https://wavesplatform.atlassian.net/browse/DEX-12

Dex 12 zero decimals

---

lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/EvaluatorV1.scala
src/main/scala/com/wavesplatform/state/diffs/SetScriptTransactionDiff.scala
src/main/scala/com/wavesplatform/state/diffs/TransactionDiffer.scala
src/main/scala/com/wavesplatform/transaction/smart/script/v1/ScriptV1.scala
src/test/scala/com/wavesplatform/state/diffs/smart/predef/ScriptVersionsTest.scala

NODE-1263-no-check-DupNames-after-SmartTrading

---

src/main/scala/com/wavesplatform/state/NgState.scala

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-1289](https://wavesplatform.atlassian.net/browse/NODE-1289)

NODE-1289: Fix microblock diff issue

---

it/src/main/scala/com/wavesplatform/it/api/AsyncHttpApi.scala
it/src/main/scala/com/wavesplatform/it/matcher/MatcherSuiteBase.scala
it/src/test/scala/com/wavesplatform/it/sync/matcher/config/MatcherPriceAssetConfig.scala
it/src/test/scala/com/wavesplatform/it/sync/matcher/smartcontracts/OrdersFromScriptedAccTestSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/matcher/smartcontracts/OrdersFromScriptedAssetTestSuite.scala
src/main/scala/com/wavesplatform/matcher/Matcher.scala
src/main/scala/com/wavesplatform/matcher/market/OrderBookActor.scala
src/main/scala/com/wavesplatform/matcher/model/ExchangeTransactionCreator.scala
src/main/scala/com/wavesplatform/matcher/model/OrderValidator.scala
src/main/scala/com/wavesplatform/state/diffs/CommonValidation.scala
src/main/scala/com/wavesplatform/state/diffs/ExchangeTransactionDiff.scala
src/main/scala/com/wavesplatform/transaction/ValidationError.scala
src/main/scala/com/wavesplatform/transaction/assets/exchange/OrderType.scala
src/main/scala/com/wavesplatform/transaction/smart/Verifier.scala
src/test/scala/com/wavesplatform/matcher/market/OrderValidatorSpecification.scala

* OrderValidator checks an order against the fake one

DEX-155 Smart assets trading

---

lang/jvm/src/main/scala/com/wavesplatform/utils/DocExport.scala
lang/jvm/src/test/scala/com/wavesplatform/lang/Common.scala
lang/jvm/src/test/scala/com/wavesplatform/lang/EvaluatorV1Test.scala
lang/jvm/src/test/scala/com/wavesplatform/lang/IntegrationTest.scala
lang/jvm/src/test/scala/com/wavesplatform/lang/TypeInferrerTest.scala
lang/jvm/src/test/scala/com/wavesplatform/lang/compiler/CompilerV1Test.scala
lang/jvm/src/test/scala/com/wavesplatform/lang/compiler/package.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/compiler/Types.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/PureContext.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/converters/package.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/package.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/waves/Types.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/waves/WavesContext.scala
src/main/scala/com/wavesplatform/matcher/smart/MatcherContext.scala
src/test/scala/com/wavesplatform/state/diffs/smart/predef/CommonFunctionsTest.scala

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-1254](https://wavesplatform.atlassian.net/browse/NODE-1254)

NODE-1254: Unit removed from TYPE ADT

---

it/src/test/scala/com/wavesplatform/it/sync/smartcontract/smartasset/AssetSupportedTransactionsSuite.scala

Node-1223 Check of generating balance after leasing

NODE-1221 AssetSupported transactions

---

src/main/scala/com/wavesplatform/transaction/Signed.scala

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-1255](https://wavesplatform.atlassian.net/browse/NODE-1255)

NODE-1255: better sig-validator scheduler configuration

---

src/main/scala/com/wavesplatform/database/Caches.scala
src/main/scala/com/wavesplatform/database/LevelDBWriter.scala
src/main/scala/com/wavesplatform/utx/UtxPoolImpl.scala

JIRA: https://wavesplatform.atlassian.net/browse/NODE-1248
Added logging for
* New address IDs and `lastAddressId`
* Transactions put into and rejected from UTX pool

NODE-1248 Added logging to track changes to address IDs

---

it/src/main/scala/com/wavesplatform/it/MatcherNode.scala
it/src/main/scala/com/wavesplatform/it/api/AsyncHttpApi.scala
it/src/main/scala/com/wavesplatform/it/api/SyncHttpApi.scala
it/src/main/scala/com/wavesplatform/it/api/SyncMatcherHttpApi.scala
it/src/main/scala/com/wavesplatform/it/matcher/MatcherSuiteBase.scala
it/src/test/scala/com/wavesplatform/it/sync/matcher/BlacklistedTradingTestSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/matcher/smartcontracts/ExtraFeeTestSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/matcher/smartcontracts/ProofAndAssetPairTestSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/smartcontract/smartasset/AssetSupportedTransactionsSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/smartcontract/smartasset/ExchangeTransactionSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/transactions/SetAssetScriptTransactionSuite.scala
project/Dependencies.scala
src/main/scala/com/wavesplatform/matcher/model/ExchangeTransactionCreator.scala
src/main/scala/com/wavesplatform/matcher/model/OrderValidator.scala
src/main/scala/com/wavesplatform/state/diffs/CommonValidation.scala
src/test/scala/com/wavesplatform/state/diffs/ExchangeTransactionDiffTest.scala

* Fee calculated correctly during order's placing and ExchangeTransaction's creation;
* Added ExtraFeeTestSuite.

DEX-155 Smart asset trade fee fixes and tests

---

it/src/main/scala/com/wavesplatform/it/MatcherNode.scala
lang/jvm/src/main/scala/com/wavesplatform/lang/JavaAdapter.scala
lang/jvm/src/main/scala/com/wavesplatform/utils/DocExport.scala
lang/jvm/src/test/scala/com/wavesplatform/lang/EvaluatorV1Test.scala
lang/jvm/src/test/scala/com/wavesplatform/lang/v1/ScriptEstimatorTest.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/compiler/CompilerV1.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/waves/Bindings.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/waves/Types.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/waves/WavesContext.scala
src/main/scala/com/wavesplatform/matcher/model/OrderValidator.scala
src/main/scala/com/wavesplatform/matcher/smart/MatcherContext.scala
src/main/scala/com/wavesplatform/matcher/smart/MatcherScriptRunner.scala
src/main/scala/com/wavesplatform/transaction/smart/BlockchainContext.scala
src/main/scala/com/wavesplatform/transaction/smart/Verifier.scala
src/main/scala/com/wavesplatform/transaction/smart/script/ScriptRunner.scala
src/main/scala/com/wavesplatform/utils/package.scala
src/test/scala/com/wavesplatform/state/diffs/ProduceError.scala
src/test/scala/com/wavesplatform/state/diffs/smart/predef/ScriptVersionsTest.scala
src/test/scala/com/wavesplatform/state/diffs/smart/predef/TransactionBindingsTest.scala
src/test/scala/com/wavesplatform/state/diffs/smart/predef/package.scala

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-1306](https://wavesplatform.atlassian.net/browse/NODE-1306)

NODE-1306: Add parameter to enable/disable proofs in context

---

src/main/resources/application.conf

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-1298](https://wavesplatform.atlassian.net/browse/NODE-1298)

NODE-1298: Decrease block ban timeout

---

it/src/main/scala/com/wavesplatform/it/MatcherNode.scala
it/src/test/scala/com/wavesplatform/it/sync/transactions/SetAssetScriptTransactionSuite.scala
src/main/resources/application.conf
src/main/scala/com/wavesplatform/mining/Miner.scala
src/main/scala/com/wavesplatform/settings/MinerSettings.scala
src/test/scala/com/wavesplatform/settings/MinerSettingsSpecification.scala

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-1271](https://wavesplatform.atlassian.net/browse/NODE-1271)

NODE-1271: Increase interval between mining attempts if quorum not available

---

src/main/resources/application.conf

akka-settings-variants

---

src/main/scala/com/wavesplatform/state/BlockchainUpdaterImpl.scala

Increase store time for transactions in hashset 2h -> 4h

NODE-1326-store-time-for-transactions

---

it/src/test/scala/com/wavesplatform/it/sync/UtxSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/smartcontract/smartasset/AssetSupportedTransactionsSuite.scala

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-1328](https://wavesplatform.atlassian.net/browse/NODE-1328)

NODE-1328: Fix UtxSuite

---

lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/EvaluatorV1.scala

NODE-1263-no-check-DupNames-by-other-way

---

it/src/test/scala/com/wavesplatform/it/sync/matcher/smartcontracts/OrdersFromScriptedAssetTestSuite.scala

And refactor OrdersFromScriptedAssetTestSuite to reduce waiting.

DEX-168 Expired orders with smart assets

---

it/src/test/scala/com/wavesplatform/it/sync/smartcontract/ExchangeWithContractsSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/smartcontract/package.scala
it/src/test/scala/com/wavesplatform/it/sync/smartcontract/smartasset/AssetSupportedTransactionsSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/smartcontract/smartasset/ExchangeSmartAssetsSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/smartcontract/smartasset/NoOrderProofsSuite.scala
lang/js/src/main/scala/JsAPI.scala
lang/jvm/src/main/scala/com/wavesplatform/lang/JavaAdapter.scala
lang/jvm/src/main/scala/com/wavesplatform/utils/DocExport.scala
lang/jvm/src/test/scala/com/wavesplatform/lang/EvaluatorV1Test.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/compiler/Terms.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/waves/Types.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/waves/WavesContext.scala
src/main/scala/com/wavesplatform/matcher/model/OrderValidator.scala
src/main/scala/com/wavesplatform/transaction/smart/BlockchainContext.scala
src/main/scala/com/wavesplatform/transaction/smart/Verifier.scala
src/main/scala/com/wavesplatform/transaction/smart/script/ScriptRunner.scala
src/main/scala/com/wavesplatform/utils/package.scala
src/test/scala/com/wavesplatform/state/diffs/smart/predef/ScriptVersionsTest.scala
src/test/scala/com/wavesplatform/state/diffs/smart/predef/TransactionBindingsTest.scala
src/test/scala/com/wavesplatform/state/diffs/smart/predef/package.scala

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-1324](https://wavesplatform.atlassian.net/browse/NODE-1324)

NODE-1324: Get rid of unsupported transactions in Smart Asset script context

---

it/src/test/scala/com/wavesplatform/it/sync/matcher/smartcontracts/OrdersFromScriptedAccTestSuite.scala
src/main/resources/application.conf
src/main/scala/com/wavesplatform/Importer.scala
src/main/scala/com/wavesplatform/mining/Miner.scala
src/main/scala/com/wavesplatform/settings/BlockchainSettings.scala
src/main/scala/com/wavesplatform/state/appender/package.scala
src/main/scala/com/wavesplatform/utx/MatcherUtxPool.scala
src/main/scala/com/wavesplatform/utx/UtxPool.scala
src/main/scala/com/wavesplatform/utx/UtxPoolImpl.scala
src/test/scala/com/wavesplatform/settings/BlockchainSettingsSpecification.scala
src/test/scala/com/wavesplatform/settings/TestFunctionalitySettings.scala
src/test/scala/com/wavesplatform/state/diffs/BlockDifferTest.scala
src/test/scala/com/wavesplatform/utx/UtxPoolSpecification.scala

No check order of transaction while block is validated.

NODE-1319-stop-checking-txs-order

---

src/main/resources/application.conf
src/main/scala/com/wavesplatform/Explorer.scala
src/main/scala/com/wavesplatform/database/LevelDBWriter.scala
src/main/scala/com/wavesplatform/history/StorageFactory.scala
src/main/scala/com/wavesplatform/settings/WavesSettings.scala

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-1342](https://wavesplatform.atlassian.net/browse/NODE-1342)

NODE-1342: Store balance snapshots longer than other

---

it/src/test/scala/com/wavesplatform/it/sync/AssetDistributionSuite.scala
src/main/resources/application.conf
src/main/scala/com/wavesplatform/api/http/assets/AssetsApiRoute.scala
src/main/scala/com/wavesplatform/database/LevelDBWriter.scala
src/main/scala/com/wavesplatform/settings/RestAPISettings.scala
src/main/scala/com/wavesplatform/state/Blockchain.scala
src/main/scala/com/wavesplatform/state/BlockchainUpdaterImpl.scala
src/main/scala/com/wavesplatform/state/reader/CompositeBlockchain.scala
src/main/scala/com/wavesplatform/utils/EmptyBlockchain.scala
src/test/scala/com/wavesplatform/settings/RestAPISettingsSpecification.scala

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-1352](https://wavesplatform.atlassian.net/browse/NODE-1352)

NODE-1352: Pagination for assetDistribution(atHeight) api methods

---

src/main/scala/com/wavesplatform/database/LevelDBWriter.scala

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-1355](https://wavesplatform.atlassian.net/browse/NODE-1355)

NODE-1355: Fix error message

---

src/main/scala/com/wavesplatform/matcher/market/OrderBookActor.scala
src/main/scala/com/wavesplatform/matcher/market/OrderHistoryActor.scala
src/main/scala/com/wavesplatform/settings/RestAPISettings.scala

Allows to inspect order's changes.

DEX-178 Additional logs on DEX

---

src/main/scala/com/wavesplatform/history/StorageFactory.scala

New storage version isn't actual for mainnet.

dont-rebild-state-for-smartasset

---

src/main/scala/com/wavesplatform/api/http/assets/AssetsApiRoute.scala
src/main/scala/com/wavesplatform/database/Caches.scala

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-1368](https://wavesplatform.atlassian.net/browse/NODE-1368)

NODE-1368: Fix rollback error message

---

src/main/resources/application.conf
src/main/scala/com/wavesplatform/matcher/market/MatcherActor.scala
src/main/scala/com/wavesplatform/matcher/queue/KafkaMatcherQueue.scala
src/test/scala/com/wavesplatform/settings/MatcherSettingsSpecification.scala

* Buffer requests;
* Settings for producer;
* Deny snapshot creation at start;

DEX-184 Producer additional fixes

---

src/main/resources/application.conf
src/main/scala/com/wavesplatform/matcher/LocalQueueStore.scala
src/main/scala/com/wavesplatform/matcher/MatcherKeys.scala
src/main/scala/com/wavesplatform/matcher/queue/LocalMatcherQueue.scala
src/test/scala/com/wavesplatform/settings/MatcherSettingsSpecification.scala

* Limit max elements per poll;
* Cleaning before consume;

DEX-173 Production ready local queue

---

src/main/scala/com/wavesplatform/api/http/CompositeHttpService.scala

Add x-api-key headers to allowed list.

cors-allow-x-api-key

---

src/main/scala/com/wavesplatform/api/http/BlocksApiRoute.scala

JIRA: https://wavesplatform.atlassian.net/browse/NODE-1377
Now returns 400 if
- block count is 0 or negative
- count >= block height (so we're attempting to go past genesis block)

NODE-1377 GET /blocks/delay/{signature}/{blockNum} returns Internal server error

---

src/main/scala/com/wavesplatform/api/http/SignedMessage.scala

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-1370](https://wavesplatform.atlassian.net/browse/NODE-1370)

Inconsistent JsPath

---

benchmark/src/test/scala/com/wavesplatform/lang/v1/EnvironmentFunctionsBenchmark.scala
generator/src/main/scala/com.wavesplatform.generator/NarrowTransactionGenerator.scala
it/src/test/scala/com/wavesplatform/it/sync/transactions/MassTransferTransactionSuite.scala
lang/js/src/main/scala/JsAPI.scala
lang/js/src/main/scala/com/wavesplatform/lang/WavesContext.scala
lang/js/src/main/scala/com/wavesplatform/lang/impl/Environment.scala
lang/jvm/src/main/scala/com/wavesplatform/utils/DocExport.scala
lang/jvm/src/test/scala/com/wavesplatform/lang/Common.scala
lang/jvm/src/test/scala/com/wavesplatform/lang/EvaluatorV1Test.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/waves/WavesContext.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/traits/Environment.scala
src/main/scala/com/wavesplatform/account/Alias.scala
src/main/scala/com/wavesplatform/api/http/alias/AliasApiRoute.scala
src/main/scala/com/wavesplatform/api/http/alias/SignedCreateAliasV1Request.scala
src/main/scala/com/wavesplatform/api/http/alias/SignedCreateAliasV2Request.scala
src/main/scala/com/wavesplatform/transaction/TransactionFactory.scala
src/main/scala/com/wavesplatform/transaction/assets/IssueTransactionV2.scala
src/main/scala/com/wavesplatform/transaction/assets/ReissueTransactionV2.scala
src/main/scala/com/wavesplatform/transaction/assets/SetAssetScriptTransaction.scala
src/main/scala/com/wavesplatform/transaction/lease/LeaseCancelTransactionV2.scala
src/main/scala/com/wavesplatform/transaction/smart/SetScriptTransaction.scala
src/main/scala/com/wavesplatform/transaction/smart/WavesEnvironment.scala
src/test/scala/com/wavesplatform/TransactionGen.scala
src/test/scala/com/wavesplatform/account/AccountOrAliasTests.scala
src/test/scala/com/wavesplatform/account/AliasSpecification.scala
src/test/scala/com/wavesplatform/state/diffs/smart/predef/AddressTest.scala
src/test/scala/com/wavesplatform/state/diffs/smart/predef/TransactionBindingsTest.scala
src/test/scala/com/wavesplatform/state/diffs/smart/predef/package.scala
src/test/scala/com/wavesplatform/transaction/CreateAliasTransactionSpecification.scala
src/test/scala/tools/GenesisBlockGenerator.scala

Names _chainId_, _scheme_ and _networkByte_ made consistent

NODE-1270 chainId consistent name

---

src/main/scala/com/wavesplatform/utx/UtxPoolImpl.scala

NODE-1400: UTX pool bytes metric

---

src/main/scala/com/wavesplatform/state/appender/ExtensionAppender.scala

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-1435](https://wavesplatform.atlassian.net/browse/NODE-1435)

NODE-1435: Unnecessary logging

---

it/src/test/scala/com/wavesplatform/it/sync/AssetDistributionSuite.scala
src/main/scala/com/wavesplatform/api/http/assets/AssetsApiRoute.scala
src/main/scala/com/wavesplatform/database/LevelDBWriter.scala

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-1407](https://wavesplatform.atlassian.net/browse/NODE-1407)

NODE-1407 AssetDistribution Response

---

it/src/test/scala/com/wavesplatform/it/sync/MinerStateTestSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/smartcontract/HodlContractTransactionSuite.scala
src/main/scala/com/wavesplatform/api/http/ApiError.scala

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-1340](https://wavesplatform.atlassian.net/browse/NODE-1340)

NODE-1340: Transaction not allowed by script errors

---

src/main/scala/com/wavesplatform/http/ApiMarshallers.scala

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-1433](https://wavesplatform.atlassian.net/browse/NODE-1433)

NODE-1433: Disable json pretty printing

---

src/test/scala/com/wavesplatform/state/diffs/ContractInvocationTransactionDiffTest.scala

SC-8-diff-test

---

it/src/main/scala/com/wavesplatform/it/api/AsyncMatcherHttpApi.scala
it/src/test/scala/com/wavesplatform/it/async/matcher/CorrectStatusAfterPlaceTestSuite.scala
src/main/scala/com/wavesplatform/matcher/AddressActor.scala

DEX-228 NotFound error

---

src/main/scala/com/wavesplatform/matcher/market/OrderBookActor.scala

* Snapshot won't be saved for same offset

DEX-235 Fix OrderBookActorSpecification

---

lang/js/src/main/scala/JsAPI.scala
lang/jvm/src/test/scala/com/wavesplatform/lang/compiler/DecompilerTest.scala
lang/shared/src/main/scala/com/wavesplatform/lang/utils/package.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/BaseGlobal.scala
src/main/scala/com/wavesplatform/transaction/smart/script/ScriptCompiler.scala

[JIRA: https://wavesplatform.atlassian.net/browse/SC-43](https://wavesplatform.atlassian.net/browse/SC-43)
This branch is checked out from sc-59. Merge after [PR#1889](https://github.com/wavesplatform/Waves/pull/1889).

SC-43: Non-boolean return type

---

lang/js/src/main/scala/JsAPI.scala
lang/jvm/src/test/scala/com/wavesplatform/lang/compiler/DecompilerTest.scala
lang/shared/src/main/scala/com/wavesplatform/lang/utils/package.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/BaseGlobal.scala
src/main/scala/com/wavesplatform/transaction/smart/script/ScriptCompiler.scala

[JIRA: https://wavesplatform.atlassian.net/browse/SC-59](https://wavesplatform.atlassian.net/browse/SC-59)

SC-59: Directive support in JS Api

---

it/src/test/scala/com/wavesplatform/it/sync/smartcontract/ContractInvocationTransactionSuite.scala
lang/jvm/src/test/scala/com/wavesplatform/lang/ContractIntegrationTest.scala
lang/jvm/src/test/scala/com/wavesplatform/lang/compiler/ContractCompilerTest.scala
lang/jvm/src/test/scala/com/wavesplatform/lang/compiler/ExpressionCompilerV1Test.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/PureContext.scala

NODE-1487 Renamed ByteStr to ByteVector in RIDE

---

dexgenerator/src/main/scala/com/wavesplatform/dexgen/DexGenApp.scala
dexgenerator/src/main/scala/com/wavesplatform/dexgen/Worker.scala
dexgenerator/src/main/scala/com/wavesplatform/dexgen/utils/Gen.scala
generator/src/main/scala/com.wavesplatform.generator/MultisigTransactionGenerator.scala
generator/src/main/scala/com.wavesplatform.generator/NarrowTransactionGenerator.scala
generator/src/main/scala/com.wavesplatform.generator/OracleTransactionGenerator.scala
generator/src/main/scala/com.wavesplatform.generator/SmartGenerator.scala
generator/src/main/scala/com.wavesplatform.generator/utils/Gen.scala
src/test/scala/com/wavesplatform/state/diffs/smart/predef/TransactionBindingsTest.scala

Fixed timestamps of transactions in generator

---

src/main/scala/com/wavesplatform/database/LevelDBWriter.scala

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-1498](https://wavesplatform.atlassian.net/browse/NODE-1498)

NODE-1498: TransactionByAddress pagination fix

---

src/main/scala/com/wavesplatform/database/LevelDBWriter.scala

This reverts commit 3a0850a37892b744486b16ad3bb27729dbaba76e.

Revert "Fast-fix tx-by-address"

---

src/main/scala/com/wavesplatform/database/Caches.scala
src/main/scala/com/wavesplatform/database/LevelDBWriter.scala
src/test/scala/com/wavesplatform/http/AddressRouteSpec.scala
src/test/scala/com/wavesplatform/http/UtilsRouteSpec.scala

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-1498](https://wavesplatform.atlassian.net/browse/NODE-1498)
Fixes #107 
Fixes #1794

NODE-1498: TransactionByAddress

---

src/main/scala/com/wavesplatform/api/http/AddressApiRoute.scala
src/main/scala/com/wavesplatform/api/http/assets/AssetsApiRoute.scala
src/main/scala/com/wavesplatform/state/Blockchain.scala
src/main/scala/com/wavesplatform/state/BlockchainUpdaterImpl.scala
src/main/scala/com/wavesplatform/state/package.scala
src/main/scala/com/wavesplatform/state/reader/CompositeBlockchain.scala
src/test/scala/com/wavesplatform/history/BlockchainUpdaterInMemoryDiffTest.scala
src/test/scala/com/wavesplatform/state/diffs/AssetTransactionsDiffTest.scala
src/test/scala/com/wavesplatform/state/diffs/BlockDifferTest.scala
src/test/scala/com/wavesplatform/state/diffs/DataTransactionDiffTest.scala
src/test/scala/com/wavesplatform/state/diffs/ExchangeTransactionDiffTest.scala
src/test/scala/com/wavesplatform/state/diffs/smart/scenarios/ScriptedSponsorTest.scala
src/test/scala/com/wavesplatform/state/reader/StateReaderEffectiveBalancePropertyTest.scala

Replaced with `balance` and `leaseBalance`

NODE-1485 Avoid calls to `Blockchain.portfolio` wherever complete portfolio is not needed

---

lang/js/src/main/scala/JsAPI.scala

1. Context aware function and type documentation
2. Access to contract limits 
3. Access to script directive information
4. Removed unnecessary top level JS exports

JS API improvments

---

lang/jvm/src/main/scala/com/wavesplatform/utils/DocExport.scala
lang/jvm/src/test/scala/com/wavesplatform/lang/IntegrationTest.scala
lang/jvm/src/test/scala/com/wavesplatform/lang/TypeInferrerTest.scala
lang/jvm/src/test/scala/com/wavesplatform/lang/compiler/ExpressionCompilerV1Test.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/compiler/Types.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/FunctionIds.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/NativeFunction.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/PureContext.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/package.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/waves/Types.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/waves/WavesContext.scala
src/main/scala/com/wavesplatform/matcher/smart/MatcherContext.scala
src/test/scala/com/wavesplatform/state/diffs/smart/predef/ContextFunctionsTest.scala

utf8 and integer deserialisations functions.

SC-93-new-functons

---

benchmark/src/test/scala/com/wavesplatform/state/StateSyntheticBenchmark.scala
lang/js/src/main/scala/JsAPI.scala
lang/shared/src/main/scala/com/wavesplatform/lang/StdLibVersion.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/waves/WavesContext.scala
src/main/scala/com/wavesplatform/transaction/smart/BlockchainContext.scala
src/main/scala/com/wavesplatform/transaction/smart/script/ContractScript.scala
src/main/scala/com/wavesplatform/transaction/smart/script/ScriptCompiler.scala
src/main/scala/com/wavesplatform/transaction/smart/script/v1/ExprScript.scala
src/main/scala/com/wavesplatform/utils/package.scala
src/test/scala/com/wavesplatform/state/diffs/AssetTransactionsDiffTest.scala
src/test/scala/com/wavesplatform/state/diffs/smart/performance/SigVerifyPerformanceTest.scala
src/test/scala/com/wavesplatform/state/diffs/smart/predef/ContextFunctionsTest.scala
src/test/scala/com/wavesplatform/state/diffs/smart/predef/ObsoleteTransactionBindingsTest.scala
src/test/scala/com/wavesplatform/state/diffs/smart/predef/ScriptVersionsTest.scala
src/test/scala/com/wavesplatform/state/diffs/smart/predef/SerContextFunctionsTest.scala
src/test/scala/com/wavesplatform/state/diffs/smart/predef/package.scala
src/test/scala/com/wavesplatform/state/diffs/smart/scenarios/MultiSig2of3Test.scala
src/test/scala/com/wavesplatform/state/diffs/smart/scenarios/NotaryControlledTransferScenarioTest.scala
src/test/scala/com/wavesplatform/state/diffs/smart/scenarios/OnlyTransferIsAllowedTest.scala
src/test/scala/com/wavesplatform/state/diffs/smart/scenarios/OracleDataTest.scala
src/test/scala/com/wavesplatform/state/diffs/smart/scenarios/TransactionFieldAccessTest.scala
src/test/scala/com/wavesplatform/transaction/smart/script/ScriptCompilerV1Test.scala

Move new user sunctions to the V3 context.

SC-93-new-functons-fix

---

src/main/scala/com/wavesplatform/state/diffs/TransferTransactionDiff.scala
src/test/scala/com/wavesplatform/state/diffs/TransferTransactionDiffTest.scala

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-1455](https://wavesplatform.atlassian.net/browse/NODE-1455)

NODE-1455: Fix Transfer overflow check

---

src/main/scala/com/wavesplatform/transaction/assets/IssueTransactionV2.scala
src/test/scala/com/wavesplatform/transaction/IssueTransactionV2Specification.scala

SC-144-check-script-type

---

src/main/scala/com/wavesplatform/Explorer.scala

- `AP address`: dump an account portfolio
- `APS`: dump all WAVES and assets balances (takes about an hour)

NODE-1456 Added two new modes to Explorer

---

src/main/scala/com/wavesplatform/GenesisBlockGenerator.scala

There was only one way to generate genesis config for custom blockchain - checkout node source and run sbt command, now it's possible using release jar.

Accessible GenesisBlockGenerator

---

it/src/main/scala/com/wavesplatform/it/Docker.scala
it/src/main/scala/com/wavesplatform/it/api/AsyncMatcherHttpApi.scala
it/src/main/scala/com/wavesplatform/it/api/SyncMatcherHttpApi.scala
it/src/test/scala/com/wavesplatform/it/sync/matcher/MultipleMatchersTestSuite.scala
src/main/resources/application.conf
src/main/scala/com/wavesplatform/matcher/Matcher.scala
src/main/scala/com/wavesplatform/matcher/api/MatcherApiRoute.scala
src/main/scala/com/wavesplatform/matcher/queue/KafkaMatcherQueue.scala
src/test/scala/tools/KafkaTopicInfo.scala

Also:
* Way to retrieve the latest offset from queue through REST API;
* Tool for reading events from Kafka topic;

DEX-269 MultipleMatchersTestSuite fails because one of nodes doesn't consume all events

---

it/src/test/scala/com/wavesplatform/it/sync/smartcontract/smartasset/ExchangeSmartAssetsSuite.scala
it/src/test/scala/com/wavesplatform/it/sync/transactions/SponsorshipSuite.scala
src/main/scala/com/wavesplatform/settings/Constants.scala
src/main/scala/com/wavesplatform/state/diffs/CommonValidation.scala
src/test/scala/com/wavesplatform/state/diffs/SponsorshipDiffTest.scala

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-1550](https://wavesplatform.atlassian.net/browse/NODE-1550)

NODE-1550: More understandable error message

---

src/main/scala/com/wavesplatform/matcher/AddressActor.scala
src/main/scala/com/wavesplatform/matcher/Matcher.scala
src/main/scala/com/wavesplatform/matcher/market/OrderBookActor.scala
src/main/scala/com/wavesplatform/matcher/model/OrderBook.scala
src/main/scala/com/wavesplatform/matcher/queue/QueueEventWithMeta.scala

* Better logging;
Also did in this branch:
* DEX-281 Ask timeout exception for second cancel;
* DEX-282 Order book wasn't restored from snapshot;
So please use merge rather than squash.

 DEX-274 Order not found issue

---

lang/jvm/src/test/scala/com/wavesplatform/lang/compiler/names/NameDuplicationTest.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/compiler/ContractCompiler.scala

Do not fail checking for functions without annotations.

SC-160-fix-userfunctions-arguments-check

---

src/main/scala/com/wavesplatform/matcher/api/MatcherApiRoute.scala
src/main/scala/com/wavesplatform/matcher/market/MatcherActor.scala
src/main/scala/com/wavesplatform/matcher/market/OrderBookActor.scala
src/main/scala/com/wavesplatform/matcher/model/EventSerializers.scala
src/test/scala/com/wavesplatform/matcher/market/MatcherActorSpecification.scala

* Ability to create an order book before processing commands;
* MatcherApiRoute: checking the order book is started before processing a first request to this order book;
* Unit test.

DEX-289 Start an order book before place or cancel

---

dex/src/main/scala/com/wavesplatform/matcher/Matcher.scala
node/src/main/resources/application.conf
node/src/main/scala/com/wavesplatform/Importer.scala
node/src/main/scala/com/wavesplatform/api/common/CommonTransactionsApi.scala
node/src/main/scala/com/wavesplatform/api/http/assets/AssetsBroadcastApiRoute.scala
node/src/main/scala/com/wavesplatform/http/BroadcastRoute.scala
node/src/main/scala/com/wavesplatform/network/UtxPoolSynchronizer.scala
node/src/main/scala/com/wavesplatform/settings/UtxSettings.scala
node/src/main/scala/com/wavesplatform/utx/UtxPool.scala
node/src/main/scala/com/wavesplatform/utx/UtxPoolImpl.scala
node/src/test/scala/com/wavesplatform/http/AliasBroadcastRouteSpec.scala
node/src/test/scala/com/wavesplatform/http/AssetsBroadcastRouteSpec.scala
node/src/test/scala/com/wavesplatform/http/AssetsRouteSpec.scala
node/src/test/scala/com/wavesplatform/http/LeaseBroadcastRouteSpec.scala
node/src/test/scala/com/wavesplatform/http/PaymentRouteSpec.scala
node/src/test/scala/com/wavesplatform/mining/BlockWithMaxBaseTargetTest.scala
node/src/test/scala/com/wavesplatform/settings/UTXSettingsSpecification.scala
node/src/test/scala/com/wavesplatform/utx/UtxPoolSpecification.scala

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-1553](https://wavesplatform.atlassian.net/browse/NODE-1553)

Node 1553 tx rebroadcast

---

node/src/main/scala/com/wavesplatform/state/diffs/ExchangeTransactionDiff.scala

SC-115-calculate-scripts-run-fix

---

it/src/test/scala/com/wavesplatform/it/sync/transactions/DataTransactionSuite.scala
src/main/scala/com/wavesplatform/serialization/Deser.scala
src/main/scala/com/wavesplatform/transaction/Proofs.scala

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-1580](https://wavesplatform.atlassian.net/browse/NODE-1580)

NODE-1580: Proofs ser/de

---

it/src/test/scala/com/wavesplatform/it/sync/transactions/SponsorshipSuite.scala

https://wavesplatform.atlassian.net/browse/NODE-1550

Node 1550 not enough sponsored fee test

---

src/main/resources/application.conf
src/main/scala/com/wavesplatform/matcher/Matcher.scala
src/main/scala/com/wavesplatform/matcher/MatcherSettings.scala
src/main/scala/com/wavesplatform/matcher/WatchDistributedCompletionActor.scala
src/main/scala/com/wavesplatform/matcher/market/MatcherActor.scala
src/main/scala/com/wavesplatform/matcher/market/OrderBookActor.scala
src/test/scala/com/wavesplatform/matcher/market/MatcherActorSpecification.scala
src/test/scala/com/wavesplatform/matcher/market/OrderBookActorSpecification.scala
src/test/scala/com/wavesplatform/settings/MatcherSettingsSpecification.scala

* AddressActor is notified about its orders after last event processed;
* Implemented a general pattern for waiting responses from multiple workers: WatchDistributedCompletionActor;

DEX-295 Don't schedule expiration during recovery process

---

node/src/main/scala/com/wavesplatform/Importer.scala
node/src/main/scala/com/wavesplatform/http/DebugApiRoute.scala
node/src/main/scala/com/wavesplatform/mining/MiningConstraint.scala
node/src/main/scala/com/wavesplatform/state/appender/ExtensionAppender.scala
node/src/main/scala/com/wavesplatform/state/appender/package.scala
node/src/main/scala/com/wavesplatform/utx/UtxPool.scala
node/src/main/scala/com/wavesplatform/utx/UtxPoolImpl.scala
node/src/test/scala/com/wavesplatform/http/AliasBroadcastRouteSpec.scala
node/src/test/scala/com/wavesplatform/http/AssetsBroadcastRouteSpec.scala
node/src/test/scala/com/wavesplatform/http/AssetsRouteSpec.scala
node/src/test/scala/com/wavesplatform/http/LeaseBroadcastRouteSpec.scala
node/src/test/scala/com/wavesplatform/http/PaymentRouteSpec.scala
node/src/test/scala/com/wavesplatform/mining/BlockWithMaxBaseTargetTest.scala
node/src/test/scala/com/wavesplatform/utx/UtxPoolSpecification.scala

NODE-1608: UTX dont validate txs from discarded microblock and incremental diff cleanup

---

project/Dependencies.scala
src/main/scala/com/wavesplatform/matcher/Matcher.scala
src/main/scala/com/wavesplatform/matcher/MatcherTool.scala
src/main/scala/com/wavesplatform/matcher/market/MatcherActor.scala

* Also MatcherTool.mas/maj to inspect MatcherActor snapshot and journal respectively;

DEX-305 Starting issues

---

src/main/scala/com/wavesplatform/matcher/api/MatcherApiRoute.scala

Fixed GET /orderbook/{amountAsset}/{priceAsset}/status

DEX-253 For reversed pairs URLs with suffix returns incorrect redirect response

---

node/src/main/scala/com/wavesplatform/api/http/AddressApiRoute.scala
node/src/test/scala/com/wavesplatform/http/AddressRouteSpec.scala

[JIRA: https://wavesplatform.atlassian.net/browse/NODE-1626](https://wavesplatform.atlassian.net/browse/NODE-1626)

NODE-1626: Key regex filtering

---

it/src/test/scala/com/wavesplatform/it/sync/matcher/BlacklistedTradingTestSuite.scala
src/main/scala/com/wavesplatform/matcher/AssetPairBuilder.scala
src/main/scala/com/wavesplatform/matcher/api/MatcherApiRoute.scala

Also removed blacklisting checks during order book deletion.

DEX-318 REST API pair validation doesn't respect allowed-asset-pairs and white-list-only

---

it/src/main/scala/com/wavesplatform/it/api/model.scala
it/src/test/scala/com/wavesplatform/it/sync/matcher/TradersTestSuite.scala
src/main/scala/com/wavesplatform/matcher/Matcher.scala
src/main/scala/com/wavesplatform/matcher/api/MatcherApiRoute.scala
src/main/scala/com/wavesplatform/matcher/model/OrderValidator.scala
src/test/scala/com/wavesplatform/matcher/AssetPairBuilderSpec.scala
src/test/scala/com/wavesplatform/matcher/market/OrderValidatorSpecification.scala

Also removed pair validation from OrderValidator. Now it's in AssetPairBuilder

DEX-314 Hide blacklisted assets in market list

---

dex-it/src/test/scala/com/wavesplatform/it/sync/MatcherRulesTestSuite.scala
dex/src/main/scala/com/wavesplatform/matcher/Matcher.scala
dex/src/main/scala/com/wavesplatform/matcher/MatcherTool.scala
dex/src/main/scala/com/wavesplatform/matcher/market/ExchangeTransactionBroadcastActor.scala
dex/src/main/scala/com/wavesplatform/matcher/market/OrderBookActor.scala
dex/src/main/scala/com/wavesplatform/matcher/model/OrderBook.scala
dex/src/main/scala/com/wavesplatform/matcher/settings/EventsQueueSettings.scala
dex/src/main/scala/com/wavesplatform/matcher/settings/ExchangeTransactionBroadcastSettings.scala
dex/src/main/scala/com/wavesplatform/matcher/settings/MatcherSettings.scala
dex/src/main/scala/com/wavesplatform/matcher/settings/MatchingRules.scala
dex/src/test/scala/com/wavesplatform/matcher/market/ExchangeTransactionBroadcastActorSpecification.scala
dex/src/test/scala/com/wavesplatform/matcher/market/MatcherActorSpecification.scala
dex/src/test/scala/com/wavesplatform/matcher/market/OrderBookActorSpecification.scala
dex/src/test/scala/com/wavesplatform/matcher/model/MatchingRulesSpecification.scala
dex/src/test/scala/com/wavesplatform/matcher/model/OrderBookSpec.scala
dex/src/test/scala/com/wavesplatform/matcher/settings/MatcherSettingsSpecification.scala
node/src/main/scala/com/wavesplatform/settings/package.scala
node/src/main/scala/com/wavesplatform/settings/utils/ConfigOps.scala
node/src/main/scala/com/wavesplatform/settings/utils/ConfigSettingsValidator.scala

Order cancelling after changing of the tick size was fixed

DEX-317 Order cancelling fix

---

node/src/test/scala/com/wavesplatform/state/diffs/TransactionValidationErrorPrintTest.scala

Test for string and big bytestr representation.

SC-331-pretty-byte-string-test

---

lang/jvm/src/test/scala/com/wavesplatform/lang/IntegrationTest.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/CryptoContext.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/PureContext.scala

fixed arg types and names in NotImplemented error texts

SC-342 fixed lastIndexOf() with max long offset

---

node/src/main/scala/com/wavesplatform/Application.scala
node/src/main/scala/com/wavesplatform/Importer.scala
node/src/main/scala/com/wavesplatform/metrics/Metrics.scala
node/src/main/scala/com/wavesplatform/network/ChannelClosedHandler.scala
node/src/main/scala/com/wavesplatform/network/DiscardingHandler.scala
node/src/main/scala/com/wavesplatform/network/MessageObserver.scala
node/src/main/scala/com/wavesplatform/state/BlockchainUpdaterImpl.scala
node/src/main/scala/com/wavesplatform/utils/Schedulers.scala
node/src/main/scala/com/wavesplatform/utils/Time.scala
node/src/main/scala/com/wavesplatform/utx/UtxPoolImpl.scala

[JIRA: https://jira.wavesplatform.com/browse/NODE-1772](https://jira.wavesplatform.com/browse/NODE-1772)

NODE-1772: RejectedExecution fix

---

build.sbt
dex/build.sbt
node/build.sbt
node/src/package/debian/postrm
project/CommonSettings.scala
project/ExtensionKeys.scala
project/ExtensionPackaging.scala

DEX-308 Install with DEB

---

node-it/src/test/scala/com/wavesplatform/it/api/AsyncHttpApi.scala
node-it/src/test/scala/com/wavesplatform/it/api/SyncHttpApi.scala
node-it/src/test/scala/com/wavesplatform/it/api/model.scala
node-it/src/test/scala/com/wavesplatform/it/sync/transactions/IssueNFTSuite.scala
node/src/main/scala/com/wavesplatform/state/package.scala

https://jira.wavesplatform.com/browse/NODE-1814

NODE-1814: Fix NFT API

---

lang/jvm/src/main/scala/com/wavesplatform/utils/Merkle.scala
lang/jvm/src/test/scala/com/wavesplatform/utils/MerkleTest.scala

[JIRA: https://jira.wavesplatform.com/browse/SC-399](https://jira.wavesplatform.com/browse/SC-399)

SC-399: Fix merkle proofs parsing

---

node/src/main/scala/com/wavesplatform/Exporter.scala

[JIRA: https://jira.wavesplatform.com/browse/NODE-1823](https://jira.wavesplatform.com/browse/NODE-1823)

NODE-1823: Shutdown kamon

---

node/src/main/scala/com/wavesplatform/block/BlockField.scala

[JIRA: https://jira.wavesplatform.com/browse/NODE-1804](https://jira.wavesplatform.com/browse/NODE-1804)

NODE-1804: Add generator public key to blockheader json

---

node/src/main/scala/com/wavesplatform/api/common/CommonTransactionsApi.scala
node/src/main/scala/com/wavesplatform/state/diffs/CommonValidation.scala
node/src/main/scala/com/wavesplatform/state/diffs/FeeValidation.scala
node/src/main/scala/com/wavesplatform/state/diffs/TransactionDiffer.scala
node/src/test/scala/com/wavesplatform/state/diffs/CommonValidationTest.scala

[JIRA: https://jira.wavesplatform.com/browse/NODE-1812](https://jira.wavesplatform.com/browse/NODE-1812)

NODE-1812: Insufficient fee error enriched

---

node-it/src/test/scala/com/wavesplatform/it/sync/ForgeReturnedToUTXSuite.scala
node-it/src/test/scala/com/wavesplatform/it/sync/ForgeReturnedToUtxSuite.scala

utx should be cleaned after rejected mircoblock txs returned to utx
https://jira.wavesplatform.com/browse/NODE-1835

Node 1835 utx cleaner test

---

grpc-server/src/main/scala/com/wavesplatform/api/grpc/PBImplicitConversions.scala
grpc-server/src/main/scala/com/wavesplatform/api/grpc/TransactionsApiGrpcImpl.scala
node/src/main/scala/com/wavesplatform/protobuf/transaction/PBRecipients.scala
node/src/main/scala/com/wavesplatform/protobuf/transaction/PBTransactions.scala

>Wrong addressBytes length: expected: 26, actual: 32

NODE-1855: gRPC address conversions fixes

---

node-it/src/test/scala/com/wavesplatform/it/api/AsyncHttpApi.scala
node-it/src/test/scala/com/wavesplatform/it/api/SyncHttpApi.scala
node-it/src/test/scala/com/wavesplatform/it/sync/block/BlockHeadersTestSuite.scala

[JIRA: https://jira.wavesplatform.com/browse/NODE-1833](https://jira.wavesplatform.com/browse/NODE-1833)

NODE-1833: Blocks by address API

---

node-it/src/test/scala/com/wavesplatform/it/sync/RollbackSuite.scala

https://jira.wavesplatform.com/browse/NODE-1857

NODE-1857 rollback suite fix

---

node-it/src/test/scala/com/wavesplatform/it/sync/smartcontract/InvokeScriptTransactionStateChangesSuite.scala

[JIRA: https://jira.wavesplatform.com/browse/NODE-1809](https://jira.wavesplatform.com/browse/NODE-1809)

NODE-1809: Debug State Changes API

---

node/src/main/scala/com/wavesplatform/block/Block.scala
node/src/main/scala/com/wavesplatform/state/package.scala

[JIRA: https://jira.wavesplatform.com/browse/NODE-1864](https://jira.wavesplatform.com/browse/NODE-1864)

NODE-1864: Read header instead of block

---

node/src/main/resources/application.conf

JIRA: https://jira.wavesplatform.com/browse/NODE-1875

NODE-1875: Default API key

---

README.md

Added recommended cloning method. 
See details https://help.github.com/en/articles/which-remote-url-should-i-use#cloning-with-https-urls-recommended

[*] fixed Added recommended cloning method. 

---

.github/ISSUE_TEMPLATE/feature_request.md

Removes one not needed space character

Fixes typo in issue template

---

releaseJenkinsfile

Added publishing artifacts in APT repository

addAptRepoCode

---

lang/shared/src/main/scala/com/wavesplatform/lang/script/ScriptReader.scala

Jira: https://jira.wavesplatform.com/browse/NODE-1791

NODE-1791: Error message

---

releaseJenkinsfile

allowAnyHosts

---

blockchain-updates/src/main/protobuf/events.proto

Fix import for blockchain-updates

DATA-1039 fix event.proto (import)

---

node-it/src/test/scala/com/wavesplatform/it/sync/RewardsTestSuite.scala
node/src/test/scala/com/wavesplatform/history/BlockRewardSpec.scala

1. Activation tests (miner doesn't get reward and GET /blockchain/rewards returns 400 before activation)
2. Miner's balance increases as he generates block after feature activation

Additional tests for block reward feature

---

node/src/main/scala/com/wavesplatform/Application.scala
node/src/main/scala/com/wavesplatform/database/LevelDBWriter.scala
node/src/main/scala/com/wavesplatform/network/FatalErrorHandler.scala
node/src/main/scala/com/wavesplatform/utils/package.scala
node/src/test/scala/com/wavesplatform/mining/BlockWithMaxBaseTargetTest.scala
node/src/test/scala/com/wavesplatform/transaction/BlockchainUpdaterTest.scala

JIRA: https://jira.wavesplatform.com/browse/NODE-1903

NODE-1903: Uncaught exceptions handling

---

node-it/src/test/scala/com/wavesplatform/it/sync/RollbackSuite.scala
node/src/main/scala/com/wavesplatform/Application.scala
node/src/main/scala/com/wavesplatform/http/DebugApiRoute.scala
node/src/main/scala/com/wavesplatform/network/HistoryReplier.scala
node/src/main/scala/com/wavesplatform/utils/ScorexLogging.scala
node/src/test/scala/com/wavesplatform/http/DebugApiRouteSpec.scala

Hide exceptions from HistoryReplier

---

docker/Dockerfile
releaseJenkinsfile

1. тут поменял метод сборки, чтобы привести к единому во всех пайплайнах.
2. в паре мест были описки
3. в пайплайне изменил "node/assembly" на "true", чтобы быстрее собирались пакеты.

Release jenkinsfile improvements

---

node/src/test/scala/com/wavesplatform/history/BlockRewardSpec.scala

- Negative block reward vote
- Null block reward vote

Additional unit tests for block reward

---

lang/tests/src/test/scala/com/wavesplatform/lang/IntegrationTest.scala
node-it/src/test/scala/com/wavesplatform/it/api/AsyncHttpApi.scala
node-it/src/test/scala/com/wavesplatform/it/api/SyncHttpApi.scala
node-it/src/test/scala/com/wavesplatform/it/api/model.scala
node-it/src/test/scala/com/wavesplatform/it/sync/grpc/CreateAliasTransactionGrpcSuite.scala
node-it/src/test/scala/com/wavesplatform/it/sync/grpc/IssueTransactionGrpcSuite.scala
node-it/src/test/scala/com/wavesplatform/it/sync/grpc/SetScriptTransactionGrpcSuite.scala
node-it/src/test/scala/com/wavesplatform/it/sync/package.scala
node-it/src/test/scala/com/wavesplatform/it/sync/transactions/AliasTransactionSuite.scala
node/src/main/scala/com/wavesplatform/protobuf/transaction/PBTransactions.scala

1. Tests for gRPC IssueTransaction
2. Fix script validation error in PBTransactions.createVanilla()

NODE-1938: IssueTransaction gRPC tests and PBTransactions fix

---

node/src/main/scala/com/wavesplatform/api/common/CommonTransactionsApi.scala
node/src/main/scala/com/wavesplatform/api/http/TransactionsApiRoute.scala
node/src/main/scala/com/wavesplatform/block/Block.scala
node/src/main/scala/com/wavesplatform/block/merkle/Merkle.scala
node/src/main/scala/com/wavesplatform/block/package.scala
node/src/test/scala/com/wavesplatform/block/TransactionsRootSpec.scala
node/src/test/scala/com/wavesplatform/http/TransactionsRouteSpec.scala

Jira: 
https://jira.wavesplatform.com/browse/NODE-1983
https://jira.wavesplatform.com/browse/NODE-1972

NODE-1983: Transactions merkle root API

---

node-it/src/test/scala/com/wavesplatform/it/sync/BlockV5TestSuite.scala
node/src/main/scala/com/wavesplatform/consensus/PoSSelector.scala
node/src/main/scala/com/wavesplatform/features/FeatureProvider.scala
node/src/main/scala/com/wavesplatform/mining/Miner.scala
node/src/main/scala/com/wavesplatform/state/appender/package.scala
node/src/test/scala/com/wavesplatform/mining/BlockV5Test.scala

Jira: https://jira.wavesplatform.com/browse/NODE-1991

NODE-1991: Block version validation

---

node/src/main/scala/com/wavesplatform/Exporter.scala
node/src/main/scala/com/wavesplatform/Importer.scala
node/src/main/scala/com/wavesplatform/metrics/BlockStats.scala
node/src/main/scala/com/wavesplatform/state/BlockchainUpdaterImpl.scala

[JIRA: https://jira.wavesplatform.com/browse/NODE-1976](https://jira.wavesplatform.com/browse/NODE-1976)
[JIRA: https://jira.wavesplatform.com/browse/NODE-1930](https://jira.wavesplatform.com/browse/NODE-1930)

NODE-1976/1930

---

node-it/src/test/scala/com/wavesplatform/it/api/AsyncHttpApi.scala
node-it/src/test/scala/com/wavesplatform/it/api/SyncHttpApi.scala
node/src/main/scala/com/wavesplatform/api/http/AddressApiRoute.scala
node/src/main/scala/com/wavesplatform/database/LevelDBWriter.scala
node/src/main/scala/com/wavesplatform/state/Blockchain.scala
node/src/main/scala/com/wavesplatform/state/BlockchainUpdaterImpl.scala
node/src/main/scala/com/wavesplatform/state/reader/CompositeBlockchain.scala
node/src/main/scala/com/wavesplatform/utils/EmptyBlockchain.scala

From NODE-1974-api-balances-on-height

NODE-1974-api-balances-on-height-v17

---

node-it/src/test/scala/com/wavesplatform/it/api/model.scala
node-it/src/test/scala/com/wavesplatform/it/sync/transactions/TransactionsStatusSuite.scala

Jira: https://jira.wavesplatform.com/browse/NODE-1934

NODE-1934: Integration test for '/transactions/status' method

---

lang/js/src/main/scala/JsAPI.scala
lang/shared/src/main/scala/com/wavesplatform/lang/utils/package.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/compiler/CompilerContext.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/compiler/Types.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/EvaluatorV1.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/PureContext.scala
lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/waves/Types.scala
lang/tests/src/test/scala/com/wavesplatform/lang/IntegrationTest.scala

Add and handle hideConstructor filend to the CASETYPEREF class.

SC-492-hide-some-constructor

---

node/src/main/scala/com/wavesplatform/api/http/assets/AssetsApiRoute.scala
node/src/test/scala/com/wavesplatform/api/http/AssetsApiRouteSpec.scala

https://jira.wavesplatform.com/browse/NODE-2017

NODE-2017: '/asset/details/{assetId}' route fix

---

node-it/src/test/scala/com/wavesplatform/it/api/model.scala
node/src/main/scala/com/wavesplatform/block/serialization/BlockSerializer.scala

https://jira.wavesplatform.com/browse/NODE-2018

NODE-2018: Block json representation

---

node/src/main/scala/com/wavesplatform/consensus/PoSSelector.scala
node/src/main/scala/com/wavesplatform/mining/Miner.scala

https://jira.wavesplatform.com/browse/NODE-2024

NODE-2024: Block delay calculation

---

node/src/main/scala/com/wavesplatform/Exporter.scala

https://jira.wavesplatform.com/browse/NODE-2016

NODE-2016: Exporter height argument

---

node/src/main/scala/com/wavesplatform/network/BasicMessagesRepo.scala
node/src/main/scala/com/wavesplatform/transaction/DataTransaction.scala
node/src/main/scala/com/wavesplatform/transaction/validation/impl/DataTxValidator.scala
node/src/test/scala/com/wavesplatform/transaction/DataTransactionSpecification.scala

https://jira.wavesplatform.com/browse/NODE-2038

NODE-2038: Data transaction size limit

---

node/src/main/scala/com/wavesplatform/api/http/TransactionsApiRoute.scala
node/src/test/scala/com/wavesplatform/block/TransactionsRootSpec.scala
node/src/test/scala/com/wavesplatform/http/TransactionsRouteSpec.scala

https://jira.wavesplatform.com/browse/NODE-2043

NODE-2043: Merkle proofs in Base58

---

node/src/main/resources/application.conf

Typo error on line 101
Treansaction (wrong)
Transaction (correct)

Typo error correction on application.conf

---

node-it/src/test/scala/com/wavesplatform/it/api/model.scala
node-it/src/test/scala/com/wavesplatform/it/sync/BlockV5TestSuite.scala

https://jira.wavesplatform.com/browse/NODE-2036

NODE-2036: VRF in block header integration test

---

node/src/main/scala/com/wavesplatform/api/common/CommonTransactionsApi.scala
node/src/main/scala/com/wavesplatform/api/http/TransactionsApiRoute.scala
node/src/main/scala/com/wavesplatform/block/Block.scala
node/src/main/scala/com/wavesplatform/block/merkle/Merkle.scala
node/src/main/scala/com/wavesplatform/block/package.scala
node/src/test/scala/com/wavesplatform/block/TransactionsRootSpec.scala
node/src/test/scala/com/wavesplatform/http/TransactionsRouteSpec.scala

https://jira.wavesplatform.com/browse/NODE-2055

NODE-2055: Transactions merkle tree

---

node-it/src/test/scala/com/wavesplatform/it/sync/grpc/BlockV5GrpcSuite.scala
node/src/main/scala/com/wavesplatform/features/FeatureProvider.scala
node/src/main/scala/com/wavesplatform/state/appender/package.scala
node/src/test/scala/com/wavesplatform/mining/BlockV5Test.scala

https://jira.wavesplatform.com/browse/NODE-1991

NODE-1991: Version check

---

blockchain-updates/src/main/protobuf/events.proto
blockchain-updates/src/main/scala/com/wavesplatform/events/protobuf/PBEvents.scala
node/src/main/scala/com/wavesplatform/events/BlockchainUpdateTriggers.scala
node/src/main/scala/com/wavesplatform/events/BlockchainUpdateTriggersImpl.scala
node/src/main/scala/com/wavesplatform/events/events.scala
node/src/main/scala/com/wavesplatform/state/BlockchainUpdaterImpl.scala
node/src/test/scala/com/wavesplatform/events/BlockchainUpdateTriggersImplSpec.scala
node/src/test/scala/com/wavesplatform/events/BlockchainUpdateTriggersSpec.scala
node/src/test/scala/com/wavesplatform/events/EventsHelpers.scala
node/src/test/scala/com/wavesplatform/events/GenesisBlockUpdateSpec.scala
node/src/test/scala/com/wavesplatform/state/BlockchainUpdaterImplSpec.scala

Sending updated Waves amount with the blockchain updates events

Data 1180 send waves amount updates

---

node/src/main/scala/com/wavesplatform/state/diffs/InvokeScriptTransactionDiff.scala
node/src/test/scala/com/wavesplatform/state/diffs/ci/InvokeScriptTransactionDiffTest.scala
node/src/test/scala/com/wavesplatform/state/diffs/package.scala

https://jira.wavesplatform.com/browse/NODE-2068

NODE-2068: Asset id uniqueness

---

node/src/main/scala/com/wavesplatform/transaction/TxValidationError.scala
node/src/test/scala/com/wavesplatform/state/diffs/MassTransferTransactionDiffTest.scala
node/src/test/scala/com/wavesplatform/state/diffs/ci/InvokeScriptTransactionDiffTest.scala
node/src/test/scala/com/wavesplatform/state/diffs/smart/scenarios/AddressFromRecipientScenarioTest.scala

SC-551-allow-alias-error-messages

---

node/src/test/scala/com/wavesplatform/transaction/ChainIdSpecification.scala

https://jira.wavesplatform.com/browse/NODE-2051

NODE-2051: Additional tests

---

node-it/src/test/scala/com/wavesplatform/it/api/AsyncHttpApi.scala
node-it/src/test/scala/com/wavesplatform/it/api/SyncHttpApi.scala
node-it/src/test/scala/com/wavesplatform/it/sync/activation/VRFProtobufActivationSuite.scala
node-it/src/test/scala/com/wavesplatform/it/sync/smartcontract/package.scala
node/src/main/scala/com/wavesplatform/state/diffs/ExchangeTransactionDiff.scala
node/src/main/scala/com/wavesplatform/transaction/validation/impl/ExchangeTxValidator.scala
node/src/test/scala/com/wavesplatform/TransactionGen.scala
node/src/test/scala/com/wavesplatform/state/diffs/ExchangeTransactionDiffTest.scala
node/src/test/scala/com/wavesplatform/transaction/ExchangeTransactionSpecification.scala

https://jira.wavesplatform.com/browse/NODE-2095

NODE-2095: ExchangeTransaction V3 orders postion

---

lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/Contextful.scala
lang/tests/src/test/scala/com/wavesplatform/lang/IntegrationTest.scala

SC-413-test

---

node-it/src/test/scala/com/wavesplatform/it/asset/IssueReissueBurnAssetSuite.scala
node/src/main/scala/com/wavesplatform/state/diffs/InvokeScriptTransactionDiff.scala
node/src/test/scala/com/wavesplatform/state/diffs/ci/InvokeScriptTransactionDiffTest.scala

SC-575-update-state-for-diffs-calculation

---

node-it/src/test/scala/com/wavesplatform/it/asset/IssueReissueBurnAssetSuite.scala
node/src/main/scala/com/wavesplatform/api/http/ApiError.scala

https://jira.wavesplatform.com/browse/NODE-2091

NODE-2091: Account balance error message on API

---

node-it/src/test/scala/com/wavesplatform/it/api/SyncHttpApi.scala
node-it/src/test/scala/com/wavesplatform/it/sync/transactions/ExchangeTransactionSuite.scala
node/src/test/scala/com/wavesplatform/transaction/ExchangeTransactionSpecification.scala

https://jira.wavesplatform.com/browse/NODE-2094

NODE-2094: ExchangeTransaction validation error messages

---

CODE_OF_CONDUCT.md
README.md

See how it will look like here:
https://github.com/KardanovIR/Waves/tree/readme-update
What was changed:
- Fixed mess in headings
- Added node run demo GIF
- Added CODE_OF_CONDUCT.md file
- Added Licence and Contributing sections
- Added Getting started section
- Fixed some broken links

Readme update

---

node-it/src/test/scala/com/wavesplatform/it/asset/IssueReissueBurnAssetSuite.scala

https://jira.wavesplatform.com/browse/NODE-2121

NODE-2121: Additional integration test

---

node/src/main/scala/com/wavesplatform/Application.scala
node/src/main/scala/com/wavesplatform/Importer.scala

https://jira.wavesplatform.com/browse/NODE-2125

NODE-2125: Extensions initializing during Import

---

benchmark/src/test/scala/com/wavesplatform/state/LevelDBWriterBenchmark.scala
grpc-server/src/main/scala/com/wavesplatform/api/grpc/BlocksApiGrpcImpl.scala
node-it/src/test/scala/com/wavesplatform/it/api/model.scala
node-it/src/test/scala/com/wavesplatform/it/sync/activation/AcceptFailedScriptActivationSuite.scala
node/src/main/scala/com/wavesplatform/Application.scala
node/src/main/scala/com/wavesplatform/Importer.scala
node/src/main/scala/com/wavesplatform/api/common/CommonBlocksApi.scala
node/src/main/scala/com/wavesplatform/api/http/BlocksApiRoute.scala
node/src/main/scala/com/wavesplatform/api/http/TransactionsApiRoute.scala
node/src/main/scala/com/wavesplatform/database/package.scala
node/src/main/scala/com/wavesplatform/http/DebugApiRoute.scala
node/src/main/scala/com/wavesplatform/state/BlockchainUpdaterImpl.scala

https://jira.wavesplatform.com/browse/NODE-2166

NODE-2166: Transactions application status in API

---

node/src/main/scala/com/wavesplatform/Application.scala

https://jira.wavesplatform.com/browse/NODE-2069

NODE-2069: Logging absence of config file

---

node-it/src/test/scala/com/wavesplatform/it/api/model.scala
node-it/src/test/scala/com/wavesplatform/it/asset/GrpcSponsorFeeActionSuite.scala
node-it/src/test/scala/com/wavesplatform/it/asset/SponsorFeeActionSuite.scala
node-it/src/test/scala/com/wavesplatform/it/sync/smartcontract/HodlContractTransactionSuite.scala
node-it/src/test/scala/com/wavesplatform/it/sync/smartcontract/InvokeScriptTransactionStateChangesSuite.scala
node/src/main/scala/com/wavesplatform/state/diffs/invoke/InvokeDiffsCommon.scala

https://jira.wavesplatform.com/browse/NODE-2159

NODE-2159: The order of state changes

---

benchmark/src/test/scala/com/wavesplatform/state/WavesEnvironmentRebenchmark.scala
node/src/main/protobuf/waves/database.proto
node/src/main/scala/com/wavesplatform/api/common/AddressTransactions.scala
node/src/main/scala/com/wavesplatform/database/Caches.scala
node/src/main/scala/com/wavesplatform/database/KeyTags.scala
node/src/main/scala/com/wavesplatform/database/Keys.scala
node/src/main/scala/com/wavesplatform/database/LevelDBWriter.scala
node/src/main/scala/com/wavesplatform/database/package.scala
node/src/main/scala/com/wavesplatform/state/Blockchain.scala
node/src/main/scala/com/wavesplatform/state/BlockchainUpdaterImpl.scala
node/src/main/scala/com/wavesplatform/state/reader/CompositeBlockchain.scala
node/src/main/scala/com/wavesplatform/transaction/smart/WavesEnvironment.scala
node/src/main/scala/com/wavesplatform/utx/UtxPoolImpl.scala
node/src/test/scala/com/wavesplatform/database/LevelDBWriterSpec.scala
node/src/test/scala/com/wavesplatform/utils/EmptyBlockchain.scala
node/src/test/scala/com/wavesplatform/utx/UtxPoolSpecification.scala

https://jira.wavesplatform.com/browse/NODE-2171

NODE-2171: Transaction status in state

---

benchmark/src/test/scala/com/wavesplatform/lang/v1/ScriptEvaluatorBenchmark.scala
node/src/main/scala/com/wavesplatform/api/common/CommonAccountsApi.scala
node/src/test/scala/com/wavesplatform/http/CommonAccountsApiSpec.scala

https://jira.wavesplatform.com/browse/NODE-2190

NODE-2190: Filtering liquid data entries

---

node/src/main/resources/application.conf

https://jira.wavesplatform.com/browse/NODE-2140

NODE-2140: Updated `min-micro-block-age`

---

node/src/main/scala/com/wavesplatform/Importer.scala
node/src/main/scala/com/wavesplatform/database/BloomFilter.scala
node/src/main/scala/com/wavesplatform/state/diffs/invoke/InvokeScriptTransactionDiff.scala

https://jira.wavesplatform.com/browse/NODE-2207

NODE-2207: Importer graceful shutdown

---

node/src/main/resources/application.conf
node/src/main/resources/swagger-ui/swagger.json
node/src/main/scala/com/wavesplatform/Application.scala
node/src/main/scala/com/wavesplatform/database/Caches.scala
node/src/main/scala/com/wavesplatform/database/KeyTags.scala
node/src/main/scala/com/wavesplatform/database/Keys.scala
node/src/main/scala/com/wavesplatform/database/LevelDBWriter.scala
node/src/main/scala/com/wavesplatform/database/package.scala
node/src/main/scala/com/wavesplatform/history/StorageFactory.scala
node/src/main/scala/com/wavesplatform/http/DebugApiRoute.scala
node/src/main/scala/com/wavesplatform/settings/DBSettings.scala
node/src/main/scala/com/wavesplatform/state/DiffToStateApplier.scala
node/src/main/scala/com/wavesplatform/state/StateHash.scala
node/src/main/scala/com/wavesplatform/state/StateHashBuilder.scala
node/src/test/scala/com/wavesplatform/http/DebugApiRouteSpec.scala
node/src/test/scala/com/wavesplatform/state/StateHashSpec.scala

https://jira.wavesplatform.com/browse/NODE-2232

NODE-2232: State hash

---

node/src/main/scala/com/wavesplatform/api/http/AddressApiRoute.scala

https://jira.wavesplatform.com/browse/NODE-2241

NODE-2241: DataEntry json streaming serialization
