wavesplatform/Waves

src/main/scala/scorex/account/Account.scala, src/main/scala/scorex/account/AccountOrAlias.scala, src/main/scala/scorex/account/Alias.scala, src/main/scala/scorex/api/http/AddressApiRoute.scala, src/main/scala/scorex/api/http/BlocksApiRoute.scala, src/main/scala/scorex/api/http/TransactionsApiRoute.scala, src/main/scala/scorex/api/http/alias/AliasApiRoute.scala, src/main/scala/scorex/api/http/alias/SignedCreateAliasRequest.scala, src/main/scala/scorex/api/http/assets/AssetsApiRoute.scala, src/main/scala/scorex/consensus/nxt/api/http/NxtConsensusApiRoute.scala, src/main/scala/scorex/transaction/SimpleTransactionModule.scala, src/main/scala/scorex/transaction/state/database/blockchain/StoredState.scala, src/main/scala/scorex/transaction/state/database/state/storage/MVStoreStateStorage.scala, src/main/scala/scorex/wallet/Wallet.scala, src/main/scala/scorex/waves/http/WavesApiRoute.scala, src/test/scala/scorex/account/AccountOrAliasTests.scala, src/test/scala/scorex/account/AccountSpecification.scala, src/test/scala/scorex/consensus/nxt/TransactionsOrderingSpecification.scala, src/test/scala/scorex/lagonaki/integration/AliasTransactionSpecification.scala, src/test/scala/scorex/lagonaki/integration/StoredStateSpecification.scala, src/test/scala/scorex/lagonaki/integration/api/PaymentAPISpecification.scala, src/test/scala/scorex/lagonaki/unit/OrderMatchStoredStateSpecification.scala, src/test/scala/scorex/lagonaki/unit/StoredStateUnitTests2.scala, src/test/scala/scorex/transaction/FeeCalculatorSpecification.scala, src/test/scala/scorex/transaction/TransactionGen.scala
- Network byte is a part of Alias
- uri-like account schemes `address:` and `alias:W` introduced for parsing and string representation of aliased recipient
=> T502 alias network byte

src/main/scala/com/wavesplatform/history/HistoryWriterImpl.scala, src/main/scala/com/wavesplatform/state2/BlockchainUpdaterImpl.scala, src/main/scala/com/wavesplatform/state2/StateStorage.scala, src/main/scala/com/wavesplatform/state2/StateWriter.scala, src/main/scala/com/wavesplatform/state2/reader/StateReaderImpl.scala, src/test/scala/com/wavesplatform/state2/reader/StateReaderEffectiveBalanceTest.scala
Node doesn't start if state is corrupt:
```
2017-05-02 12:38:08 INFO  [main] c.w.Application$ - Starting...
2017-05-02 12:38:10 INFO  [lt-dispatcher-8] a.event.slf4j.Slf4jLogger - Slf4jLogger started
2017-05-02 12:38:10 INFO  [main] c.w.Application$ - Waves v0.7.0-SNAPSHOT Blockchain Id: T
2017-05-02 12:38:10 INFO  [main] scorex.wallet.Wallet - Opening wallet from C:\Users\ilyas/waves/wallet/wallet.dat
2017-05-02 12:38:10 ERROR [main] c.w.actor.RootActorSystem$ - Error while initializing actor system wavesplatform
java.lang.IllegalArgumentException: Persisted state is corrupt, height0=24000, height=23800. Please remove state.dat and restart the node
at com.wavesplatform.state2.reader.StateReaderImpl.<init>(StateReaderImpl.scala:17)
at …
```
=> T442 state consistency check at start

src/it/scala/com/wavesplatform/it/TestFourNodesSuite.scala, src/it/scala/com/wavesplatform/it/api/NodeApi.scala, src/it/scala/com/wavesplatform/it/transactions/debug/DebugPortfoliosSpecification.scala, src/main/scala/com/wavesplatform/UtxPool.scala, src/main/scala/com/wavesplatform/state2/Portfolio.scala, src/main/scala/com/wavesplatform/state2/reader/CompositeStateReader.scala, src/main/scala/scorex/utils/Synchronized.scala, src/main/scala/scorex/waves/http/DebugApiRoute.scala, src/test/scala/com/wavesplatform/UtxPoolSpecification.scala, src/test/scala/com/wavesplatform/state2/PortfolioTest.scala
You can check a portfolio (including the balance) through a debug API-method:
```
/debug/portfolios/{address}?considerUnspent=true|false
```
, but don't forget to provide an API key ;)
* considerUnspent=*true* - including transactions from UTX pool;
* considerUnspent=*false* - without it.
=> NODE-73: Get account balance after application of transactions in UTX pool

src/main/scala/com/wavesplatform/Coordinator.scala, src/main/scala/com/wavesplatform/metrics/BlockStats.scala, src/main/scala/com/wavesplatform/metrics/TxsInBlockchainStats.scala, src/main/scala/com/wavesplatform/mining/Miner.scala, src/main/scala/com/wavesplatform/network/CoordinatorHandler.scala, src/main/scala/com/wavesplatform/network/MicroBlockSynchronizer.scala
* Fixed configuration to pass WavesSettingsSpecification tests;
* BlockStats: Rejected -> Declined;
* Send to InfluxDB events about blocks in extensions;
* Send additional data in metrics (parent's id, score, propagation time and other).
=> NODE-169: NG metrics: transactions, rollbacks, propagation

build.sbt
I've already tested this solution on devnet:
1. Specified `Xmx200m` and the `-XX:+ExitOnOutOfMemoryError` flag
2. Saw a log:
```
journalctl -u waves-devnet --since "-10m" -f | grep -E "(OutOfMemoryError|Starting\.\.\.)"
Sep 18 12:34:12 devnet1 waves-devnet[28257]: -XX:+ExitOnOutOfMemoryError
Sep 18 12:34:13 devnet1 waves-devnet[28257]: INFO  c.w.Application$ - Starting...
Sep 18 12:36:13 devnet1 waves-devnet[28257]: Terminating due to java.lang.OutOfMemoryError: GC overhead limit exceeded
Sep 18 12:37:13 devnet1 waves-devnet[28603]: -XX:+ExitOnOutOfMemoryError
Sep 18 12:37:14 devnet1 waves-devnet[28603]: INFO  c.w.Application$ - Starting...
Sep 18 12:39:18 devnet1 waves-devnet[28603]: Terminating due to java.lang.OutOfMemoryError: GC overhead limit exceeded
Sep 18 12:40:18 devnet1 …
```
=> NODE-176: Terminate the Node on java.lang.OutOfMemoryError

project/Dependencies.scala, src/main/resources/application.conf, src/main/resources/logback.xml, src/main/scala/com/wavesplatform/Application.scala
Logs after this PR:
```
2017-10-18 14:20:21 INFO  [run-main-0] c.w.Application$ - Starting...
2017-10-18 14:20:26 INFO  [run-main-0] kamon.Kamon$Instance - Initializing Kamon...
2017-10-18 14:20:26 INFO  [lt-dispatcher-2] a.event.slf4j.Slf4jLogger - Slf4jLogger started
2017-10-18 14:20:31 INFO  [lt-dispatcher-4] k.s.SystemMetricsExtension - Starting the Kamon(SystemMetrics) extension
2017-10-18 14:20:31 INFO  [run-main-0] k.sigar.SigarProvisioner - Sigar library provisioned: /Users/freezy/Projects/work/waves-platform/waves/native/libsigar-universal64-macosx.dylib
2017-10-18 14:20:31 INFO  [lt-dispatcher-3] k.i.InfluxDBExtension - Starting the Kamon(InfluxDB) extension
2017-10-18 14:20:32 INFO  [lt-dispatcher-2] a.event.slf4j.Slf4jLogger - Slf4jLogger started
2017-10-18 14:20:32 INFO …
```
=> NODE-282 One format for all NODE's logs

src/it/scala/com/wavesplatform/it/transactions/LeasingTransactionsSuite.scala, src/main/scala/scorex/api/http/TransactionsApiRoute.scala, src/main/scala/scorex/transaction/lease/LeaseTransaction.scala
[Link to JIRA](https://wavesplatform.atlassian.net/browse/NODE-379)
Note that I've named the flag "canceled" (one L) because this is the preferred American English spelling according to [Grammarly](https://www.grammarly.com/blog/canceled-vs-cancelled/)
=> NODE-379 Add "cancelled" flag to leasing transaction

src/it/scala/com/wavesplatform/it/Docker.scala, src/it/scala/com/wavesplatform/it/NodeApiTestSuite.scala, src/it/scala/com/wavesplatform/it/api/NodeApi.scala, src/main/scala/com/wavesplatform/Application.scala, src/main/scala/com/wavesplatform/Importer.scala, src/main/scala/com/wavesplatform/history/StorageFactory.scala, src/main/scala/com/wavesplatform/http/NodeApiRoute.scala, src/main/scala/com/wavesplatform/state2/BlockchainUpdaterImpl.scala, src/main/scala/com/wavesplatform/state2/StateWriter.scala, src/main/scala/scorex/transaction/BlockchainUpdater.scala, src/test/scala/com/wavesplatform/UtxPoolSpecification.scala, src/test/scala/com/wavesplatform/history/package.scala, src/test/scala/scorex/transaction/BlockchainUpdaterTest.scala
Changes:
- The REST server now starts immediately on node startup, the only endpoints supported at that time being /node/*
- /node/status returns both blockchain height and state height. This is implemented using Observables.
- I had to make BlockchainUpdaterImpl.syncPersistedAndInMemory() method public, because it was called from the ctor so it was impossible to create a BlockchainUpdater instance without rebuilding state.
- Integration tests were broken by the change, as the REST service now starts way before the node is ready to be tested. I've added a new method, NodeApi.waitForStartup(), that waits for the node to become fully operational
=> NODE-414 Extend API for /node/status + make it available at start

src/it/scala/com/wavesplatform/it/transactions/TransferTransactionSuite.scala, src/main/scala/com/wavesplatform/state2/reader/SnapshotStateReader.scala, src/main/scala/scorex/api/http/TransactionsApiRoute.scala, src/test/scala/com/wavesplatform/state2/reader/StateReaderLastTransactionsTest.scala
https://wavesplatform.atlassian.net/browse/NODE-380
Changed SnapshotStateReader to return both transactions and their heights.
=> NODE-380 Add "height" value to transactions received from API by address

src/it/scala/com/wavesplatform/it/TransactionsApiSuite.scala, src/it/scala/com/wavesplatform/it/api/NodeApi.scala, src/it/scala/com/wavesplatform/it/transactions/TransferTransactionSuite.scala, src/main/scala/com/wavesplatform/Application.scala, src/main/scala/scorex/api/http/TransactionsApiRoute.scala, src/main/scala/scorex/api/http/alias/CreateAliasRequest.scala, src/main/scala/scorex/api/http/assets/BurnRequest.scala, src/main/scala/scorex/api/http/assets/IssueRequest.scala, src/main/scala/scorex/api/http/assets/ReissueRequest.scala, src/main/scala/scorex/api/http/assets/TransferRequest.scala, src/main/scala/scorex/api/http/leasing/LeaseCancelRequest.scala, src/main/scala/scorex/api/http/leasing/LeaseRequest.scala, src/main/scala/scorex/transaction/TransactionFactory.scala, src/test/scala/com/wavesplatform/http/TransactionsRouteSpec.scala
https://wavesplatform.atlassian.net/browse/NODE-387
Changes:
- Added /transactions/sign endpoint for signing transactions of all types. This endpoint is protected with API key and supports an optional timestamp parameter. If no timestamp is specified, server time is used.
- Added another endpoint, /transactions/broadcast, for publishing signed transactions.
=> NODE-387 Create API two methods to sign and broadcast transactions

src/it/scala/com/wavesplatform/it/transactions/TransferTransactionSuite.scala, src/main/scala/com/wavesplatform/state2/diffs/CommonValidation.scala
JIRA: https://wavesplatform.atlassian.net/browse/NODE-416
The fix is to compare Long values instead of Durations
=> NODE-416 API returs error 500 if timestamp in json is too large

src/main/scala/com/wavesplatform/Application.scala, src/main/scala/com/wavesplatform/Importer.scala, src/main/scala/com/wavesplatform/history/HistoryWriterImpl.scala, src/main/scala/com/wavesplatform/history/StorageFactory.scala, src/main/scala/com/wavesplatform/http/NodeApiRoute.scala, src/main/scala/com/wavesplatform/state2/BlockchainUpdaterImpl.scala, src/main/scala/com/wavesplatform/state2/StateStorage.scala, src/main/scala/com/wavesplatform/state2/StateWriter.scala, src/main/scala/com/wavesplatform/utils/package.scala, src/main/scala/scorex/transaction/BlockchainUpdater.scala, src/main/scala/scorex/transaction/History.scala, src/main/scala/scorex/transaction/NgHistoryReader.scala, src/test/scala/com/wavesplatform/UtxPoolSpecification.scala, src/test/scala/com/wavesplatform/history/package.scala, src/test/scala/com/wavesplatform/network/TestHistory.scala, src/test/scala/scorex/transaction/BlockchainUpdaterTest.scala
JIRA: https://wavesplatform.atlassian.net/browse/NODE-467
- In NodeApiRoute, replaced StateWriter and BlockchainUpdater references with Coevals
- Got rid of nodeApiLauncher callback
=> NODE-467 Stop exposing internal entities to NodeApiRoute

src/it/scala/com/wavesplatform/it/TransactionsApiSuite.scala, src/main/scala/scorex/api/http/assets/SignedBurnRequest.scala, src/main/scala/scorex/api/http/leasing/SignedLeaseCancelRequest.scala
Additional fix for https://wavesplatform.atlassian.net/browse/NODE-387
I'm working around differences in field naming:
"amount" in BurnTransaction but "quantity" in SignedBurnRequest
"leaseId" in LeaseCancelTransaction but "txId" in SignedLeaseCancelRequest
The solution proposed is to provide custom JSON deserializers for SignedRequest classes so that they accept both variants
=> NODE-387 Fixed broadcast of burn and lease cancel requests

it/src/main/scala/com/wavesplatform/it/api/AsyncHttpApi.scala, src/main/resources/application.conf, src/main/resources/swagger-ui/index.html, src/main/scala/com/wavesplatform/http/api_key.scala, src/main/scala/scorex/api/http/ApiRoute.scala, src/main/scala/scorex/api/http/CompositeHttpService.scala, src/test/scala/com/wavesplatform/http/DebugApiRouteSpec.scala, src/test/scala/com/wavesplatform/http/WalletRouteSpec.scala
=> NODE-483 api_key is deprecated, X-API-Key is preferred

it/src/test/scala/com/wavesplatform/it/transactions/LeasingTransactionsSuite.scala, src/main/scala/com/wavesplatform/Application.scala, src/main/scala/com/wavesplatform/state2/reader/CompositeStateReader.scala, src/main/scala/scorex/api/http/leasing/LeaseApiRoute.scala
JIRA: https://wavesplatform.atlassian.net/browse/NODE-520
A new API endpoint was introduced: GET /leasing/active/{address} . It returns list of all active outgoing leases from that address.
I've also fixed a bug in CompositeStateReader.activeLeases(): when `blockDiff.txsDiff.leaseState` and the inner state report different states for a lease, the former should win
=> NODE-520 API method to return all active leasing transaction

it/src/test/scala/com/wavesplatform/it/TransactionsApiSuite.scala, src/main/scala/scorex/api/http/assets/SignedTransferRequest.scala
...so that JSON returned from /transactions/sign can be fed right into /transactions/broadcast
=> NODE-387 leftover: accept both "feeAsset" and "feeAssetId" in SignedTransferRequest

generator/src/main/scala/com.wavesplatform.generator/utils/Gen.scala, it/src/test/scala/com/wavesplatform/it/transactions/MassTransferTransactionSuite.scala, src/main/scala/com/wavesplatform/network/BasicMessagesRepo.scala
Fixed propagation of MassTransfer transactions:
- Increased `TransactionSpec.maxLength`
- Created a test
- Made sure Generator specifies sufficient fee
=> Node 494 mass transfer api

it/src/test/scala/com/wavesplatform/it/sync/transactions/LeaseStatusTestSuite.scala, src/main/scala/com/wavesplatform/state2/reader/CompositeStateReader.scala
JIRA: https://wavesplatform.atlassian.net/browse/NODE-619
In CompositeStateReader:
```
override def allActiveLeases = diff.leaseState
.collect { case (id, true) => diff.transactions(id)._2 }
.collect { case lt: LeaseTransaction => lt }
.toSet ++ inner.allActiveLeases
```
Problem is, if a lease is canceled in `diff.leaseState` but not in `inner.allActiveLeases`, it will be returned as active. We need to filter such just recently canceled leases from `inner.allActiveLeases`
=> NODE-619 LeaseStatusTestSuite consistently fails

it/src/test/scala/com/wavesplatform/it/sync/MinerStateTestSuite.scala
Redefined sync timeout for MinerStateTestSuite, just to avoid sync issue between local nodes.
=> Small fix for sync issue for MinerStateTestSuite

it/src/main/scala/com/wavesplatform/it/api/AsyncHttpApi.scala
For investigation tricky issues it would be great 
to get params of request body in debug logs.
=> Debug logging for request body

src/test/scala/scorex/transaction/DataTransactionSpecification.scala
JIRA: https://wavesplatform.atlassian.net/browse/NODE-766
Max valid DataEntry type value is hardcoded as 3, which is wrong now as we've added String type. I'm fixing the code to use `maxId`
=> NODE-766 DataTransactionSpecification fails sometimes

it/src/test/scala/com/wavesplatform/it/async/SmartTransactionsConstraintsSuite.scala, it/src/test/scala/com/wavesplatform/it/sync/DataTransactionSuite.scala, it/src/test/scala/com/wavesplatform/it/sync/SetScriptTransactionSuite.scala, it/src/test/scala/com/wavesplatform/it/sync/transactions/SignAndBroadcastApiSuite.scala, lang/jvm/src/main/scala/com/wavesplatform/utils/Base64.scala, lang/jvm/src/test/scala/com/wavesplatform/utils/Base64Test.scala, src/main/scala/com/wavesplatform/state/ByteStr.scala, src/main/scala/com/wavesplatform/state/DataEntry.scala, src/main/scala/com/wavesplatform/utils/JsonFileStorage.scala, src/main/scala/scorex/api/http/AddressApiRoute.scala, src/main/scala/scorex/api/http/UtilsApiRoute.scala, src/main/scala/scorex/api/http/assets/SignedIssueV2Request.scala, src/main/scala/scorex/api/http/assets/SignedSetScriptRequest.scala, src/main/scala/scorex/transaction/TransactionFactory.scala, src/main/scala/scorex/transaction/smart/SetScriptTransaction.scala, src/main/scala/scorex/transaction/smart/script/Script.scala, src/test/scala/com/wavesplatform/http/AddressRouteSpec.scala, src/test/scala/com/wavesplatform/http/UtilsRouteSpec.scala
JIRA: https://wavesplatform.atlassian.net/browse/NODE-764
Changes:
- SetScript and Issue transactions accept base64-encoded scripts only
- REST API returns scripts as base64 strings
- Base64 strings must have "base64:" prefix to tell them from base58
=> NODE-764  Use base64 to encode scripts

lang/jvm/src/main/scala/com/wavesplatform/utils/Base64.scala
Explicitly check for the "base64:" prefix
=> NODE-772 Improve error reports in REST APIs that expect base64

lang/jvm/src/test/scala/com/wavesplatform/lang/IntegrationTest.scala, lang/jvm/src/test/scala/com/wavesplatform/lang/ParserTest.scala, lang/jvm/src/test/scala/com/wavesplatform/lang/typechecker/CompilerV1Test.scala, lang/jvm/src/test/scala/com/wavesplatform/lang/typechecker/ErrorTest.scala, lang/shared/src/main/scala/com/wavesplatform/lang/v1/compiler/CompilerV1.scala, lang/shared/src/main/scala/com/wavesplatform/lang/v1/parser/BinaryOperation.scala, lang/shared/src/main/scala/com/wavesplatform/lang/v1/parser/Expressions.scala, lang/shared/src/main/scala/com/wavesplatform/lang/v1/parser/Parser.scala, lang/shared/src/main/scala/com/wavesplatform/lang/v1/parser/UnaryOperation.scala, lang/shared/src/main/scala/com/wavesplatform/lang/v1/testing/ScriptGen.scala, src/test/scala/com/wavesplatform/state/diffs/smart/scenarios/OracleDataTest.scala
* Offsets in expressions;
* Parser fixes:
* NODE-700: ; and \n rules in BLOCK;
* Better accessors parsing: now it treats multiline function calls as invalid: (foo)\n(bar, baz);
* Better numbers parsing;
* NoCut for LET;
* ParserTest:
* Additional tests for BLOCK (NODE-700), tests for multiple accessors;
* More detailed information about failure.
=> NODE-745 Parser provides offsets

src/main/scala/scorex/api/http/assets/AssetsApiRoute.scala, src/main/scala/scorex/transaction/assets/IssueTransaction.scala, src/main/scala/scorex/transaction/transfer/TransferTransaction.scala, src/test/scala/scorex/api/http/AssetsApiRouteSpec.scala, src/test/scala/scorex/transaction/IssueTransactionV1Specification.scala, src/test/scala/scorex/transaction/IssueTransactionV2Specification.scala, src/test/scala/scorex/transaction/TransferTransactionV1Specification.scala, src/test/scala/scorex/transaction/TransferTransactionV2Specification.scala
Changes:
- Restored `assetId` in IssueTransaction
- Added `feeAsset` to TransferTransaction so that both `feeAssetId` are returned. The former is for compatibility, the latter just looks better
- Changed `script` and `scriptText` in `/assets/details` from `String` to `Option[String]`. If there's no script, the API now returns `null`, not `""` as before
=> NODE-773 API incompatibilities in v0.13.0

lang/jvm/src/test/scala/com/wavesplatform/lang/ParserTest.scala, lang/shared/src/main/scala/com/wavesplatform/lang/v1/parser/BinaryOperation.scala, lang/shared/src/main/scala/com/wavesplatform/lang/v1/parser/Parser.scala
Several operations (like '+' and '-', '*' and '/') have identical priority.
=> NODE-814-group-operations-by-priority

lang/jvm/src/test/scala/com/wavesplatform/lang/ParserTest.scala, lang/shared/src/main/scala/com/wavesplatform/lang/v1/parser/BinaryOperation.scala
make prioority of '<', '>', '<=', '>=' greter then priority of '==' and '!='
=> NODE-814-reorder-comparation-priority

it/src/test/scala/com/wavesplatform/it/sync/AtomicSwapSmartContractSuite.scala, lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/waves/Bindings.scala, lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/waves/Types.scala, lang/shared/src/main/scala/com/wavesplatform/lang/v1/traits/Domain.scala, src/main/scala/scorex/transaction/smart/RealTransactionWrapper.scala, src/test/scala/com/wavesplatform/state/diffs/smart/predef/TransactionBindingsTest.scala, src/test/scala/com/wavesplatform/state/diffs/smart/predef/package.scala, src/test/scala/com/wavesplatform/state/diffs/smart/scenarios/NotaryControlledTransferScenartioTest.scala, src/test/scala/com/wavesplatform/state/diffs/smart/scenarios/OnlyTransferIsAllowedTest.scala
- renamed senderPk to senderPublicKey (need careful review)
=> NODE-785 Compatibility with testnet addresses

it/src/test/scala/com/wavesplatform/it/sync/transactions/DataTransactionSuite.scala, src/main/scala/scorex/transaction/DataTransaction.scala, src/test/scala/com/wavesplatform/TransactionGen.scala, src/test/scala/scorex/transaction/DataTransactionSpecification.scala
JIRA: https://wavesplatform.atlassian.net/browse/NODE-830
The following are now prohibited:
- data transaction containing duplicate keys
- empty string as key
=> NODE-830 Prohibit to include several identical keys in data transation

lang/jvm/src/test/scala/com/wavesplatform/lang/Common.scala, lang/jvm/src/test/scala/com/wavesplatform/lang/EvaluatorV1Test.scala, lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/FunctionIds.scala, lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/CryptoContext.scala, lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/EnvironmentFunctions.scala, lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/PureContext.scala, lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/package.scala, lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/waves/WavesContext.scala, src/test/scala/com/wavesplatform/state/diffs/smart/scenarios/NotaryControlledTransferScenartioTest.scala
=> NODE-847 Implement ADDRESSFROMSTRING in RIDE

benchmark/src/test/scala/com/wavesplatform/lang/v1/ScriptEstimatorBenchmark.scala, it/src/test/scala/com/wavesplatform/it/sync/AtomicSwapSmartContractSuite.scala, lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/EvaluationContext.scala, src/main/scala/scorex/transaction/smart/script/ScriptCompiler.scala, src/main/scala/scorex/transaction/smart/script/v1/ScriptV1.scala, src/test/scala/com/wavesplatform/state/diffs/smart/scenarios/NotaryControlledTransferScenartioTest.scala, src/test/scala/com/wavesplatform/state/diffs/smart/scenarios/OracleDataTest.scala
JIRA: https://wavesplatform.atlassian.net/browse/NODE-829
Changes:
- `functionCosts` was moved inside `EvaluationContext` case class where it can access type definitions
- Cost of a data constructor is just the number of its parameters
- The rest of the changes is to tests
=> NODE-829 Updated Estimator to handle data constructors

lang/jvm/src/test/scala/com/wavesplatform/lang/ParserTest.scala, lang/shared/src/main/scala/com/wavesplatform/lang/v1/parser/Parser.scala, src/test/scala/com/wavesplatform/state/diffs/smart/predef/TransactionBindingsTest.scala
Allow \\ and \" symbols in strings.
=> NODE-605-special-symbols

src/main/scala/scorex/transaction/lease/LeaseTransaction.scala, src/main/scala/scorex/transaction/lease/LeaseTransactionV2.scala, src/test/scala/scorex/transaction/LeaseTransactionSpecification.scala
JIRA: https://wavesplatform.atlassian.net/browse/NODE-736
Added an `assetId` field to binary representation. Currently the only valid value is None.
Field order is unnatural, but see NODE-784
=> NODE-736 Allow new lease/leasecancel possibility to have AssetId field

it/src/test/scala/com/wavesplatform/it/sync/matcher/MatcherTestSuite.scala, src/main/scala/com/wavesplatform/matcher/api/MatcherApiRoute.scala, src/main/scala/com/wavesplatform/matcher/market/OrderHistoryActor.scala, src/main/scala/com/wavesplatform/matcher/model/OrderHistory.scala, src/test/scala/com/wavesplatform/matcher/market/OrderHistoryActorSpecification.scala, src/test/scala/com/wavesplatform/matcher/model/OrderHistorySpecification.scala
JIRA: https://wavesplatform.atlassian.net/browse/NODE-927
The actor from which we were asking active orders was limiting the number of orders it returned. I'm fixing that by adding an 'internal' mode where it skips some unnecessary steps such as limiting, sorting etc
=> NODE-927 Not all orders are cancelled with "Cancel All" operation

it/src/main/scala/com/wavesplatform/it/api/AsyncMatcherHttpApi.scala, it/src/main/scala/com/wavesplatform/it/api/SyncMatcherHttpApi.scala, it/src/test/scala/com/wavesplatform/it/sync/matcher/TradeBalanceAndRoundingTestSuite.scala, src/main/scala/com/wavesplatform/matcher/model/OrderHistory.scala, src/test/scala/com/wavesplatform/matcher/model/OrderHistorySpecification.scala
Fixes for:
* Negative reserved balances;
* Submitted order cancelled, but has the Accepted status;
* Cancelled orders doesn't appear in the user's order history
during the situations when submitted orders can't be matched (because of rounding).
=> NODE-1102 Negative reserved balances

it/src/test/scala/com/wavesplatform/it/sync/matcher/MatcherRestartTestSuite.scala, it/src/test/scala/com/wavesplatform/it/sync/matcher/MatcherTestSuite.scala, src/main/resources/application.conf, src/main/scala/com/wavesplatform/matcher/Matcher.scala, src/main/scala/com/wavesplatform/matcher/MatcherSettings.scala, src/main/scala/com/wavesplatform/matcher/api/JsonSerializer.scala, src/main/scala/com/wavesplatform/matcher/api/MatcherApiRoute.scala, src/main/scala/com/wavesplatform/matcher/api/MatcherResponse.scala, src/main/scala/com/wavesplatform/matcher/api/OrderBookSnapshotHttpCache.scala, src/main/scala/com/wavesplatform/matcher/market/MatcherActor.scala, src/main/scala/com/wavesplatform/matcher/market/MatcherTransactionWriter.scala, src/main/scala/com/wavesplatform/matcher/market/OrderBookActor.scala, src/main/scala/com/wavesplatform/matcher/market/OrderHistoryActor.scala, src/main/scala/com/wavesplatform/matcher/model/OrderBook.scala, src/main/scala/com/wavesplatform/matcher/model/OrderBookResult.scala, src/test/scala/com/wavesplatform/matcher/api/OrderBookSnapshotHttpCacheSpec.scala, src/test/scala/com/wavesplatform/matcher/market/MatcherActorSpecification.scala, src/test/scala/com/wavesplatform/settings/MatcherSettingsSpecification.scala
=> NODE-1075 Make order books responses faster

benchmark/src/test/scala/com/wavesplatform/state/BaseState.scala, it/src/main/scala/com/wavesplatform/it/api/AsyncHttpApi.scala, src/main/scala/com/wavesplatform/database/Caches.scala, src/main/scala/com/wavesplatform/database/Keys.scala, src/main/scala/com/wavesplatform/database/LevelDBWriter.scala, src/main/scala/com/wavesplatform/state/Blockchain.scala, src/main/scala/com/wavesplatform/state/BlockchainUpdaterImpl.scala, src/main/scala/com/wavesplatform/state/NgState.scala, src/main/scala/com/wavesplatform/state/diffs/BlockDiffer.scala, src/main/scala/com/wavesplatform/state/reader/CompositeBlockchain.scala, src/test/scala/com/wavesplatform/history/Domain.scala, src/test/scala/com/wavesplatform/state/RollbackSpec.scala, src/test/scala/com/wavesplatform/state/diffs/BlockDifferTest.scala, src/test/scala/com/wavesplatform/state/diffs/CommonValidationTest.scala, src/test/scala/com/wavesplatform/state/diffs/package.scala, src/test/scala/com/wavesplatform/transaction/NgStateTest.scala, src/test/scala/com/wavesplatform/transaction/SponsorFeeTransactionSpecification.scala
JIRA: https://wavesplatform.atlassian.net/browse/NODE-1077
We cannot calculate block fee from the block alone any more -- we need state for sponsored fees. Once we have the block fee, we need to pass 60% of it into the next block. One way to do it is via state.
Changes:
- Added `carryFee` parameter to both Blockchain and NgState
- In case of sponsorship, `carryFee` is written to the DB as one Long number. If sponsorship is not activated, this parameter is not used.
=> NODE-1077 Sponsorship rounding fixes

it/src/main/scala/com/wavesplatform/it/util/package.scala
When I use `4.999.waves` I expect value `499900000L` but it returns `4.9989999999999994E8`.
To fix the problem `4.999` value must be converted to BigDecimal.
=> NODE-1211 fix rounding for Double values in "waves" extension method

it/src/test/scala/com/wavesplatform/it/sync/transactions/SignAndBroadcastApiSuite.scala, src/main/scala/com/wavesplatform/api/http/assets/SignedSetAssetScriptRequest.scala, src/main/scala/com/wavesplatform/api/http/assets/SignedSetScriptRequest.scala, src/main/scala/com/wavesplatform/transaction/TransactionFactory.scala
JIRA: https://wavesplatform.atlassian.net/browse/NODE-1240
The fix is to treat `"script": ""` as `"script": null` in both SetScript and SetAssetScript transactions. I'm adding explicit checks for `""` in a few places
=> NODE-1240 Return readable message error for SetScript Tx with empty script

src/main/scala/com/wavesplatform/state/diffs/CommonValidation.scala, src/test/scala/com/wavesplatform/state/diffs/CommonValidationTest.scala
Fix using sponsored asset fee on smart account.
Checking asset fee on smart account no need more (after sponsorship activated).
=> NODE-1252-enable-assetfee-on-smartaccount

src/main/resources/logback.xml, src/main/scala/com/wavesplatform/transaction/smart/Verifier.scala
JIRA: https://wavesplatform.atlassian.net/browse/NODE-1162
Added script execution logging to `verifyTx` and `verifyOrder` in `Verifier`. Log level is DEBUG, off by default. To turn logging on:
```
<logger name="com.wavesplatform.transaction.smart" level="DEBUG"/>
```
=> NODE-1162 Log script execution debug info

src/main/scala/com/wavesplatform/Explorer.scala, src/main/scala/com/wavesplatform/database/Keys.scala
JIRA: https://wavesplatform.atlassian.net/browse/NODE-1291
Synchronized tag list in Explorer with that in Keys. Can't see how to make them sync automatically since most of the keys are `def‌`s
=> NODE-1291 Use key tags in LevelDB explorer

src/main/scala/com/wavesplatform/mining/Miner.scala
JIRA: https://wavesplatform.atlassian.net/browse/NODE-1246
The miner schedules a `generateOneBlockTask` with some generating balance and delay its execution. During that delay, its generating balance decreases, but it ignores that and mines using the balance stored in the task. The block it mines is invalid because it's mined too early according to the new balance. As a result, the miner's node rejects the block it has just mined.
The fix is to check generating balance right before mining the block.
=> NODE-1246 Blockchain height doesn't rise after: error mining Block

src/main/scala/com/wavesplatform/consensus/TransactionsOrdering.scala, src/test/scala/com/wavesplatform/consensus/nxt/TransactionsOrderingSpecification.scala
Sorting transactions in UTX by fee-per-byte.
Do not sort by id.
=> NODE-1319-order-by-fee-per-byte

src/test/scala/com/wavesplatform/state/RollbackSpec.scala
Test for transactions duplications if cache clean not in time.
=> NODE-1327-test-for-transactions-cache

it/src/test/scala/com/wavesplatform/it/sync/matcher/smartcontracts/OrdersFromScriptedAccTestSuite.scala, src/main/scala/com/wavesplatform/matcher/model/ExchangeTransactionCreator.scala, src/main/scala/com/wavesplatform/matcher/model/OrderValidator.scala, src/test/scala/com/wavesplatform/matcher/market/OrderValidatorSpecification.scala, src/test/scala/com/wavesplatform/matcher/model/ExchangeTransactionCreatorSpecification.scala
* ExchangeTransactionCreate creates ExchangeTransactionV1 if SmartAccountTrading hasn't been activated yet;
* OrderValidator doesn't allow to place OrderV2 if SmartAccountTrading hasn't been activated yet;
* Additional tests.
=> DEX-170 Can't create an ExchangeTransactionV2 before SmartAccountTrading activation

src/main/scala/com/wavesplatform/transaction/assets/IssueTransactionV2.scala, src/main/scala/com/wavesplatform/transaction/smart/SetScriptTransaction.scala, src/test/scala/com/wavesplatform/transaction/IssueTransactionV2Specification.scala, src/test/scala/com/wavesplatform/transaction/SetScriptTransactionSpecification.scala
JIRA: https://wavesplatform.atlassian.net/browse/NODE-1359
Added `chainId` to IssueV2 and SetScriptV1 transactions.
ReissueV2, BurnV2, and LeaseCancel transactions already report `chainId` as they should
=> NODE-1359 Add chainId to transactions info if it used in signature

benchmark/src/main/resources/logback.xml, benchmark/src/test/scala/com/wavesplatform/state/StateSyntheticBenchmark.scala, build.sbt, it/src/test/scala/com/wavesplatform/it/sync/matcher/MultipleMatchersTestSuite.scala, src/main/resources/application.conf, src/main/scala/com/wavesplatform/matcher/Matcher.scala, src/main/scala/com/wavesplatform/matcher/market/MatcherActor.scala, src/main/scala/com/wavesplatform/matcher/queue/KafkaMatcherQueue.scala, src/test/scala/com/wavesplatform/matcher/market/MatcherActorSpecification.scala
* MatcherActor child actors (OrderBook) will be stopped if an error happens inside of them. They are restarted before;
* KafkaMatcherQueue: consumer store the offset locally;
* We don't resolve old requests, those was did before restart;
Benchmarks:
* Can run on Java8;
* Fixed smart contract code in StateSyntheticBenchmark;
* Disabled logging;
=> DEX-185 Handle processing errors

src/main/scala/com/wavesplatform/Importer.scala, src/main/scala/com/wavesplatform/mining/Miner.scala, src/main/scala/com/wavesplatform/state/BlockchainUpdaterImpl.scala, src/main/scala/com/wavesplatform/state/appender/BlockAppender.scala, src/main/scala/com/wavesplatform/state/appender/MicroblockAppender.scala, src/main/scala/com/wavesplatform/state/appender/package.scala, src/main/scala/com/wavesplatform/state/diffs/BlockDiffer.scala, src/main/scala/com/wavesplatform/state/diffs/TransactionDiffer.scala, src/main/scala/com/wavesplatform/transaction/BlockchainUpdater.scala
JIRA: https://wavesplatform.atlassian.net/browse/NODE-1322
Changes:
* When miner mines a microblock, there's no need to validate it again before appending (see Miner.scala)
* In Importer, I'm adding the `-no-verify` or `-n` option that turns transaction validation off (see Importer.scala)
* The rest of changes is needed to pass the `verify` flag to TransactionDiffer where validation is done
=> NODE-1322 When new key block is appended, microblocks are validated once again

src/main/resources/application.conf, src/main/scala/com/wavesplatform/settings/UtxSettings.scala, src/main/scala/com/wavesplatform/utx/UtxPoolImpl.scala, src/test/scala/com/wavesplatform/settings/UTXSettingsSpecification.scala, src/test/scala/com/wavesplatform/utx/UtxPoolSpecification.scala
JIRA: https://wavesplatform.atlassian.net/browse/NODE-1269
The setting `waves.utx.max-transaction-age` duplicates the `CommonValidation.MaxTimePrevBlockOverTransactionDiff` consensus constant. These two have different values: 90 minutes vs 2 hours, hence the bug.
I suggest to remove the setting and use the constant everywhere instead.
=> NODE-1269 Transaction put to UTX but not in blockchain if tx is more than 1,5 hours old

src/main/scala/com/wavesplatform/http/DebugApiRoute.scala
JIRA: https://wavesplatform.atlassian.net/browse/NODE-1341
There are two relevant timeout settings:
* Request timeout can be set individually for each Akka endpoint. I'm setting request timeout for `/debug/rollback` to 15 minutes here
* Idle timeout is an Akka global setting. Can be configured using the `akka.http.server.idle-timeout` parameter
=> NODE-1341 Customize status code of /debug/rollback

it/src/main/resources/template.conf, it/src/test/scala/com/wavesplatform/it/sync/transactions/DataTransactionSuite.scala, it/src/test/scala/com/wavesplatform/it/sync/transactions/MassTransferTransactionSuite.scala, it/src/test/scala/com/wavesplatform/it/sync/transactions/SetAssetScriptTransactionSuite.scala, it/src/test/scala/com/wavesplatform/it/sync/transactions/SponsorshipSuite.scala, it/src/test/scala/com/wavesplatform/it/sync/transactions/TransferTransactionV1Suite.scala, src/main/resources/application.conf, src/main/scala/com/wavesplatform/settings/BlockchainSettings.scala, src/main/scala/com/wavesplatform/state/diffs/CommonValidation.scala, src/main/scala/com/wavesplatform/state/diffs/TransactionDiffer.scala, src/main/scala/com/wavesplatform/utx/UtxPoolImpl.scala, src/test/scala/com/wavesplatform/settings/BlockchainSettingsSpecification.scala, src/test/scala/com/wavesplatform/settings/TestFunctionalitySettings.scala, src/test/scala/com/wavesplatform/state/diffs/BlockDifferTest.scala, src/test/scala/com/wavesplatform/state/diffs/CommonValidationTimeTest.scala, src/test/scala/com/wavesplatform/utx/UtxPoolSpecification.scala, waves-devnet.conf
JIRA: https://wavesplatform.atlassian.net/browse/NODE-1269
Moved two constants from `CommonValidation`:
```
val MaxTimeTransactionOverBlockDiff: FiniteDuration     = 90.minutes
val MaxTimePrevBlockOverTransactionDiff: FiniteDuration = 2.hours
```
into config parameters:
```
max-transaction-time-back-offset = 120m
max-transaction-time-forward-offset = 90m
```
=> NODE-1269 Moved transaction back/forward time offsets into config params

src/main/resources/application.conf, src/main/scala/com/wavesplatform/Application.scala, src/main/scala/com/wavesplatform/api/http/ApiRoute.scala, src/main/scala/com/wavesplatform/api/http/CompositeHttpService.scala, src/main/scala/com/wavesplatform/matcher/LocalQueueStore.scala, src/main/scala/com/wavesplatform/matcher/Matcher.scala, src/main/scala/com/wavesplatform/matcher/MatcherSettings.scala, src/main/scala/com/wavesplatform/matcher/api/MatcherApiRoute.scala, src/main/scala/com/wavesplatform/matcher/api/MatcherResponse.scala, src/main/scala/com/wavesplatform/matcher/market/MatcherActor.scala, src/main/scala/com/wavesplatform/matcher/market/OrderBookActor.scala, src/main/scala/com/wavesplatform/matcher/queue/KafkaMatcherQueue.scala, src/main/scala/com/wavesplatform/matcher/queue/LocalMatcherQueue.scala, src/main/scala/com/wavesplatform/matcher/queue/MatcherQueue.scala, src/main/scala/com/wavesplatform/utils/ApplicationStopReason.scala, src/package/systemd.service, src/test/scala/com/wavesplatform/matcher/market/MatcherActorSpecification.scala, src/test/scala/com/wavesplatform/settings/MatcherSettingsSpecification.scala
* Respond with ServiceUnavailable during start and shutdown;
* Status is working when all events from Kafka are processed;
* Stop DEX when it can't be recovered at start;
Conditions:
* Timeout to recover order books;
* If one order book is failed to start;
=> DEX-202 Stop DEX when recovery fails

it/src/main/scala/com/wavesplatform/it/api/AsyncMatcherHttpApi.scala, it/src/main/scala/com/wavesplatform/it/api/SyncMatcherHttpApi.scala, it/src/test/scala/com/wavesplatform/it/sync/matcher/MatcherRecoveryTestSuite.scala, it/src/test/scala/com/wavesplatform/it/sync/matcher/MatcherRestartTestSuite.scala, it/src/test/scala/com/wavesplatform/it/sync/matcher/MultipleMatchersTestSuite.scala, src/main/resources/application.conf, src/main/resources/logback.xml, waves-testnet.conf
* Possible fix for consumers pausing;
* MultipleMatchersTestSuite non-conflict containers creation;
* Logging of refused connections with kafka;
* Matcher should be disabled on testnet by default;
* MatcherRecoveryTestSuite, MultipleMatchersTestSuite - wait until all events are processed;
* MultipleMatchersTestSuite - wait until offsets are equal;
* MatcherRestartTestSuite - wait until an order is present in the orderbook;
* Improved logs: showing when connection to Kafka is broken (DEBUG level);
=> DEX-237 Processing gap in MultipleMatchersTestSuite and MatcherRecoveryTestSuite

src/main/scala/com/wavesplatform/state/BlockchainUpdaterImpl.scala, src/main/scala/com/wavesplatform/state/NgState.scala, src/test/scala/com/wavesplatform/state/NgStateTest.scala
`BlockchainUpdaterImpl` is not thread safe and gets accessed from both appender and API threads. The solution is to add read/write locks.
As `NgState` is used only from inside `BlockchainUpdaterImpl` we can move locks employed by `NgState` up to `BlockchainUpdaterImpl`
=> NODE-1441 /blocks/headers/last messes up block height

src/main/scala/com/wavesplatform/network/package.scala, src/test/scala/com/wavesplatform/http/AssetsBroadcastRouteSpec.scala, src/test/scala/com/wavesplatform/http/AssetsRouteSpec.scala, src/test/scala/com/wavesplatform/http/LeaseBroadcastRouteSpec.scala, src/test/scala/com/wavesplatform/http/PaymentRouteSpec.scala
Added metric `network-broadcast-time` with an additional tag, `object`, that contains type of object being sent, such as `BlockForged`, `LocalScoreChanged`, `RawBytes` etc
=> NODE-1453 Added metric to network broadcast

src/main/scala/com/wavesplatform/database/Keys.scala, src/main/scala/com/wavesplatform/database/LevelDBWriter.scala
Instead of keeping the history, I'm just removing carry fee record for blocks below the threshold.
=> NODE-1477 Removed `carryFeeHistory` DB key

it/src/test/scala/com/wavesplatform/it/sync/matcher/DisableProducerTestSuite.scala, src/main/resources/application.conf, src/main/scala/com/wavesplatform/matcher/AddressActor.scala, src/main/scala/com/wavesplatform/matcher/Matcher.scala, src/main/scala/com/wavesplatform/matcher/api/MatcherApiRoute.scala, src/main/scala/com/wavesplatform/matcher/api/MatcherResponse.scala, src/main/scala/com/wavesplatform/matcher/queue/KafkaMatcherQueue.scala, src/main/scala/com/wavesplatform/matcher/queue/LocalMatcherQueue.scala, src/main/scala/com/wavesplatform/matcher/queue/MatcherQueue.scala, src/test/scala/com/wavesplatform/matcher/AddressActorSpecification.scala, src/test/scala/com/wavesplatform/matcher/model/OrderHistoryStub.scala, src/test/scala/com/wavesplatform/settings/MatcherSettingsSpecification.scala
* Producer implementations extracted from LocalMatcherQueue and KafkaMatcherQueue into MatcherQueue.Producer with IgnoreProducer;
* MatcherQueue.storeEvent returned Future[QueueEventWithMeta], now it is Future[Option[QueueEventWithMeta]]. See docs for further information;
* New configuration sections: local.enable-storing and kafka.producer.enable;
=> DEX-294 Ability to disable the producer

it/src/test/scala/com/wavesplatform/it/sync/matcher/OrderBookSnapshotsTestSuite.scala, it/src/test/scala/com/wavesplatform/it/sync/matcher/config/MatcherDefaultConfig.scala, src/main/scala/com/wavesplatform/matcher/Matcher.scala, src/main/scala/com/wavesplatform/matcher/api/MatcherApiRoute.scala, src/main/scala/com/wavesplatform/matcher/market/MatcherActor.scala, src/main/scala/com/wavesplatform/matcher/market/OrderBookActor.scala, src/main/scala/com/wavesplatform/matcher/market/SnapshotsState.scala, src/main/scala/com/wavesplatform/matcher/model/EventSerializers.scala, src/test/scala/com/wavesplatform/matcher/SnapshotUtils.scala, src/test/scala/com/wavesplatform/matcher/market/MatcherActorSpecification.scala, src/test/scala/com/wavesplatform/matcher/market/OrderBookActorSpecification.scala, src/test/scala/tools/KafkaTopicInfo.scala
OrderBookActor:
* Snapshot.eventNr is optional for better readability and stronger compiler guarantees;
* New event OrderBookRecovered with optional eventNr (opposite to OrderBookSnapshotUpdated);
SnapshotsState - simpler and more readable implementation;
Other:
* Unit tests;
* KafkaTopicInfo - fixed implementation with better logs and lesser parameters;
* Integration test: OrderBookSnapshotsTestSuite;
=>  DEX-291 Bad offset for new order books

src/main/scala/com/wavesplatform/matcher/market/OrderBookActor.scala, src/main/scala/com/wavesplatform/matcher/market/SnapshotsState.scala, src/test/scala/com/wavesplatform/matcher/market/MatcherActorSpecification.scala, src/test/scala/com/wavesplatform/matcher/market/SnapshotStateSpecification.scala
* Fixed a bug with next snapshot's offset calculation;
* Removing old snapshots of Order book when the new one is created;
=> DEX-304 Order books' snapshots are created too often

README.md, dex/build.sbt, grpc-server/build.sbt, node/build.sbt, node/src/main/scala/com/wavesplatform/Application.scala, project/RunApplicationSettings.scala
Common: dex, grpc-server are able to run from SBT;
README.md: contains instructions to run an extension project from SBT and IntelliJ IDEA;
SBT:
* RunApplicationSettings - add it to your project if you want to run it from SBT;
=> DEX-303 Ability to run extension projects without packaging

src/main/resources/application.conf, src/main/scala/com/wavesplatform/matcher/AddressActor.scala, src/main/scala/com/wavesplatform/matcher/Matcher.scala, src/main/scala/com/wavesplatform/matcher/MatcherKeys.scala, src/main/scala/com/wavesplatform/matcher/MatcherSettings.scala, src/main/scala/com/wavesplatform/matcher/MatcherTool.scala, src/main/scala/com/wavesplatform/matcher/db/AssetPairsDB.scala, src/main/scala/com/wavesplatform/matcher/db/OrderDB.scala, src/main/scala/com/wavesplatform/matcher/market/MatcherActor.scala, src/main/scala/com/wavesplatform/matcher/market/OrderBookActor.scala, src/main/scala/com/wavesplatform/matcher/queue/QueueEventWithMeta.scala, src/main/scala/com/wavesplatform/matcher/util/WorkingStash.scala, src/test/scala/com/wavesplatform/WithDB.scala, src/test/scala/com/wavesplatform/matcher/AddressActorSpecification.scala, src/test/scala/com/wavesplatform/matcher/db/AssetPairsDBSpec.scala, src/test/scala/com/wavesplatform/matcher/db/EmptyOrderDB.scala, src/test/scala/com/wavesplatform/matcher/db/OrderDBSpec.scala, src/test/scala/com/wavesplatform/matcher/db/TestOrderDB.scala, src/test/scala/com/wavesplatform/matcher/market/MatcherActorSpecification.scala, src/test/scala/com/wavesplatform/matcher/market/OrderBookActorSpecification.scala, src/test/scala/com/wavesplatform/matcher/matching/ReservedBalanceSpecification.scala, src/test/scala/com/wavesplatform/matcher/model/OrderHistoryStub.scala, src/test/scala/com/wavesplatform/settings/MatcherSettingsSpecification.scala
* AssetPairsDB to store, delete and retrieve known asset pairs in MatcherActor;
* A setting to not replay events from the stone age;
* MatcherActor uses AssetPairsDB;
* Added WorkingStash instead of Akka's Stash;
* Fixed unit tests;
MatcherTool:
* ma-migrate to migrate asset pairs from Akka Persistence to own DB;
* ma-inspect to inspect own DB;
* ob-compact to delete stale snapshots of order books;
* dex-compact to compact DEX's LevelDB;
=>  DEX-308 Storage for MatcherActor's known pairs

src/main/resources/application.conf, src/main/scala/com/wavesplatform/matcher/Matcher.scala, src/main/scala/com/wavesplatform/matcher/MatcherSettings.scala, src/main/scala/com/wavesplatform/matcher/model/OrderValidator.scala, src/test/scala/com/wavesplatform/matcher/market/OrderValidatorSpecification.scala, src/test/scala/com/wavesplatform/settings/MatcherSettingsSpecification.scala
* whitelist functionality is decoupled from "allowed-asset-pairs";
* "white-list-only" setting (see the application.conf for further information);
* updated unit tests;
=> DEX-313 Ability to blacklist an asset, but allow a pair with this asset

node/build.sbt
This is needed to transfer fallback version into master.
=> Version 0.17 into master

node-it/src/test/scala/com/wavesplatform/it/api/AsyncHttpApi.scala, node-it/src/test/scala/com/wavesplatform/it/api/SyncHttpApi.scala, node-it/src/test/scala/com/wavesplatform/it/api/model.scala, node-it/src/test/scala/com/wavesplatform/it/sync/smartcontract/HodlContractTransactionSuite.scala, node-it/src/test/scala/com/wavesplatform/it/sync/smartcontract/InvokeScriptTransactionStateChangesSuite.scala, node-it/src/test/scala/com/wavesplatform/it/sync/transactions/SponsorshipSuite.scala, node-it/src/test/scala/com/wavesplatform/it/sync/transactions/TransactionAPISuite.scala, node/src/main/scala/com/wavesplatform/http/DebugApiRoute.scala
Additionally changed `/stateChanges/info` API: now `stateChanges` is field of transaction object as in `stateChanges/address`
=> SC-323 tests for transactions/address and stateChanges/address APIs

dex/src/main/resources/application.conf, dex/src/main/scala/com/wavesplatform/matcher/Matcher.scala, dex/src/main/scala/com/wavesplatform/matcher/error/MatcherError.scala, dex/src/main/scala/com/wavesplatform/matcher/market/OrderBookActor.scala, dex/src/main/scala/com/wavesplatform/matcher/model/MatchingRules.scala, dex/src/main/scala/com/wavesplatform/matcher/model/OrderBook.scala, dex/src/main/scala/com/wavesplatform/matcher/model/OrderValidator.scala, dex/src/main/scala/com/wavesplatform/matcher/settings/MatcherSettings.scala, dex/src/main/scala/com/wavesplatform/matcher/settings/OrderRestrictionsSettings.scala, dex/src/test/scala/com/wavesplatform/matcher/market/MatcherActorSpecification.scala, dex/src/test/scala/com/wavesplatform/matcher/market/OrderBookActorSpecification.scala, dex/src/test/scala/com/wavesplatform/matcher/model/MatchingRulesSpecification.scala, dex/src/test/scala/com/wavesplatform/matcher/model/OrderBookSpec.scala, dex/src/test/scala/com/wavesplatform/matcher/model/OrderValidatorSpecification.scala, dex/src/test/scala/com/wavesplatform/matcher/settings/MatcherSettingsSpecification.scala, node/src/main/scala/com/wavesplatform/settings/utils/ConfigOps.scala, node/src/main/scala/com/wavesplatform/settings/utils/ConfigSettingsValidator.scala, node/src/main/scala/com/wavesplatform/transaction/assets/exchange/AssetPair.scala
* OrderBook and OrderBookActor works with rules. Worked with normalizedTickSize before, thus wasn't able to preserve matching results after restart.
* OrderBookActor is able to switch rules during the work.
MatcherSettings:
* "order-restrictions" now is a dictionary pair->rules (was a list) and used only during validation;
* "matching-rules" are rules to update a functionality of matching engine. See the application.conf in DEX for further information;
=> DEX-288 Switch matching rules during work

src/main/scala/com/wavesplatform/matcher/Matcher.scala, src/main/scala/com/wavesplatform/matcher/WatchDistributedCompletionActor.scala, src/main/scala/com/wavesplatform/matcher/market/MatcherActor.scala, src/main/scala/com/wavesplatform/matcher/market/OrderBookActor.scala, src/main/scala/com/wavesplatform/matcher/queue/KafkaMatcherQueue.scala, src/main/scala/com/wavesplatform/matcher/queue/LocalMatcherQueue.scala, src/main/scala/com/wavesplatform/matcher/queue/MatcherQueue.scala
* KafkaMatcherQueue, LocalMatcherQueue support backpressure;
* LocalMatcherQueue correctly reports the number of processed events;
MatcherQueue:
* startConsume.process must return Future[Unit] to know that all previous requests were processed to continue processing;
* Added lastProcessedOffset;
=> DEX-319 MatcherActor back-pressure

node/src/main/scala/com/wavesplatform/Application.scala, node/src/main/scala/com/wavesplatform/network/UtxPoolSynchronizer.scala, node/src/main/scala/com/wavesplatform/utils/Schedulers.scala, node/src/test/scala/com/wavesplatform/network/UtxPoolSynchronizerSpec.scala
A special time-bounded scheduler decorates all runnables and callables with a  `TimedWrapper` which kills current thread if a task takes too long to execute. This scheduler can be used with `Task`s and `Future`s. Do note however, that when you intend to run a task on this scheduler, you need to explicitly specify an async boundary (and probably also force async execution mode):
```
val future = Task(println(5)).runToFuture(scheduler, forceAsync = true)
```
=> NODE-1925: Limit UTX processing time

node-it/src/test/scala/com/wavesplatform/it/sync/grpc/UpdateAssetInfoTransactionGrpcSuite.scala
With the Go node the default value of 50 seconds does not seem to be enough.
It always takes 1 minute.
=> UpdateAssetInfo tests: increase timeout in waitForHeight
